-- Lessons for HTML & CSS Professional Certification Course (Course ID: 52)

-- Chapter 1: Introduction to Web Development (Chapter ID: 150)
INSERT INTO lesson (title, content, chapter_id, sort_order, difficulty, learning_objectives, estimated_time) VALUES 
('Welcome to Web Development', 'Welcome to your journey into web development! In this lesson, we will explore what web development is, the role of HTML and CSS, and set up your development environment.\n\n## What is Web Development?\n\nWeb development is the process of building and maintaining websites. It involves:\n- **Frontend Development**: What users see (HTML, CSS, JavaScript)\n- **Backend Development**: Server-side logic and databases\n- **Full Stack**: Both frontend and backend\n\n## HTML and CSS: The Foundation\n\n**HTML (HyperText Markup Language)** provides the structure and content of web pages.\n**CSS (Cascading Style Sheets)** controls the visual presentation and layout.\n\n## Setting Up Your Environment\n\n1. Install a code editor (VS Code recommended)\n2. Install a web browser (Chrome, Firefox, or Edge)\n3. Create your first HTML file\n\n## Exercise\nCreate a folder called "my-first-website" and create an empty file named "index.html".', 150, 1, 'Beginner', 'Understand web development basics, Set up development environment, Learn HTML and CSS roles', 30),

('How the Web Works', 'Understanding how the internet and websites work is fundamental to web development.\n\n## Client-Server Model\n\nThe web operates on a client-server model:\n- **Client**: Your web browser (Chrome, Firefox, Safari)\n- **Server**: Computers that store and serve websites\n\n## How Browsers Render Pages\n\n1. Browser sends HTTP request to server\n2. Server responds with HTML, CSS, and JavaScript files\n3. Browser parses HTML to create DOM (Document Object Model)\n4. Browser applies CSS styles\n5. JavaScript executes for interactivity\n\n## Developer Tools\n\nEvery browser has built-in developer tools:\n- Press F12 or right-click then Inspect\n- View HTML structure\n- Debug CSS styles\n- Test responsive design\n\n## Exercise\nOpen your browser developer tools and inspect a website HTML structure.', 150, 2, 'Beginner', 'Understand client-server model, Learn browser rendering, Use developer tools', 25);

-- Chapter 2: HTML5 Fundamentals (Chapter ID: 151)
INSERT INTO lesson (title, content, chapter_id, sort_order, difficulty, learning_objectives, estimated_time) VALUES 
('HTML Document Structure', 'Every HTML document follows a standard structure.\n\n## Basic HTML Template\n\n```html\n<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>My First Web Page</title>\n</head>\n<body>\n    <!-- Content goes here -->\n</body>\n</html>\n```\n\n## Key Elements Explained\n\n- DOCTYPE html: Declares HTML5 document\n- html: Root element\n- head: Metadata, title, links\n- body: Visible content\n\n## Exercise\nCreate your first complete HTML page with a title and some text in the body.', 151, 1, 'Beginner', 'Create HTML document structure, Understand DOCTYPE, Use head and body elements', 30),

('HTML Text Elements', 'HTML provides various elements for structuring text content.\n\n## Headings\n\n```html\n<h1>Main Heading (Only one per page)</h1>\n<h2>Section Heading</h2>\n<h3>Subsection Heading</h3>\n<h4>Minor Heading</h4>\n<h5>Small Heading</h5>\n<h6>Smallest Heading</h6>\n```\n\n## Paragraphs and Text Formatting\n\n```html\n<p>This is a paragraph of text.</p>\n<strong>Bold text for emphasis</strong>\n<em>Italic text for emphasis</em>\n<mark>Highlighted text</mark>\n<code>Inline code</code>\n```\n\n## Lists\n\n```html\n<ul>\n    <li>Unordered list item</li>\n</ul>\n<ol>\n    <li>Ordered list item</li>\n</ol>\n```\n\n## Exercise\nCreate a page with headings, paragraphs, and both types of lists.', 151, 2, 'Beginner', 'Use heading elements, Format text with semantic tags, Create ordered and unordered lists', 35),

('HTML Links and Images', 'Links and images make the web interactive and visual.\n\n## Links (Anchor Tags)\n\n```html\n<a href="https://example.com">Visit Example</a>\n<a href="page.html">Internal Link</a>\n<a href="#section">Jump to Section</a>\n<a href="mailto:email@example.com">Send Email</a>\n```\n\n## Images\n\n```html\n<img src="image.jpg" alt="Description of image">\n```\n\n**Important Attributes:**\n- src: Image source URL\n- alt: Alternative text (required for accessibility)\n- width and height: Dimensions\n\n## Best Practices\n\n- Always include alt text for accessibility\n- Use descriptive link text (not "click here")\n- Optimize images for web\n\n## Exercise\nCreate a page with links to your favorite websites and add 2-3 images.', 151, 3, 'Beginner', 'Create hyperlinks, Add images with proper attributes, Understand accessibility requirements', 40),

('HTML Forms', 'Forms allow users to input and submit data.\n\n## Basic Form Structure\n\n```html\n<form action="/submit" method="POST">\n    <label for="name">Name:</label>\n    <input type="text" id="name" name="name" required>\n    \n    <label for="email">Email:</label>\n    <input type="email" id="email" name="email" required>\n    \n    <button type="submit">Submit</button>\n</form>\n```\n\n## Input Types\n\n- text: Single-line text\n- email: Email with validation\n- password: Masked input\n- number: Numeric input\n- date: Date picker\n- checkbox: Multiple selections\n- radio: Single selection from group\n\n## Other Form Elements\n\n```html\n<textarea rows="4" cols="50">Multi-line text</textarea>\n<select name="choice">\n    <option value="1">Option 1</option>\n    <option value="2">Option 2</option>\n</select>\n```\n\n## Exercise\nCreate a contact form with name, email, subject dropdown, and message textarea.', 151, 4, 'Beginner', 'Create HTML forms, Use various input types, Implement form validation', 45);

-- Chapter 3: CSS3 Basics (Chapter ID: 152)
INSERT INTO lesson (title, content, chapter_id, sort_order, difficulty, learning_objectives, estimated_time) VALUES 
('Introduction to CSS', 'CSS brings your HTML to life with colors, fonts, and layouts.\n\n## Three Ways to Add CSS\n\n### 1. Inline CSS\n```html\n<p style="color: blue; font-size: 16px;">Styled paragraph</p>\n```\n\n### 2. Internal CSS\n```html\n<head>\n    <style>\n        p { color: blue; }\n    </style>\n</head>\n```\n\n### 3. External CSS (Recommended)\n```html\n<head>\n    <link rel="stylesheet" href="styles.css">\n</head>\n```\n\n## CSS Syntax\n\n```css\nselector {\n    property: value;\n}\n\n/* Example */\np {\n    color: #333333;\n    font-size: 16px;\n    line-height: 1.5;\n}\n```\n\n## Exercise\nCreate an external CSS file and link it to your HTML page. Style all paragraphs.', 152, 1, 'Beginner', 'Add CSS to HTML, Write CSS syntax, Create external stylesheet', 30),

('CSS Selectors', 'Selectors target HTML elements for styling.\n\n## Basic Selectors\n\n```css\n/* Element Selector */\np { color: blue; }\n\n/* Class Selector */\n.highlight { background: yellow; }\n\n/* ID Selector */\n#header { font-size: 24px; }\n\n/* Universal Selector */\n* { margin: 0; }\n```\n\n## Combinator Selectors\n\n```css\n/* Descendant */\ndiv p { color: red; }\n\n/* Child */\ndiv > p { color: blue; }\n\n/* Adjacent Sibling */\nh1 + p { font-weight: bold; }\n\n/* General Sibling */\nh1 ~ p { color: gray; }\n```\n\n## Specificity\n\nSpecificity determines which styles apply:\n1. Inline styles (1000)\n2. IDs (100)\n3. Classes (10)\n4. Elements (1)\n\n## Exercise\nCreate a page using all selector types. Test specificity by applying conflicting styles.', 152, 2, 'Beginner', 'Use element, class, and ID selectors, Understand combinators, Calculate specificity', 40),

('CSS Box Model', 'Every element is a box with specific properties.\n\n## Box Model Components\n\n- Content: The actual content area\n- Padding: Space between content and border\n- Border: The edge around the padding\n- Margin: Space outside the border\n\n## CSS Properties\n\n```css\n.box {\n    width: 300px;\n    height: 200px;\n    padding: 20px;\n    border: 2px solid black;\n    margin: 10px;\n}\n```\n\n## Box-Sizing\n\n```css\n/* Include padding/border in width */\n* {\n    box-sizing: border-box;\n}\n```\n\n## Exercise\nCreate boxes with different padding, borders, and margins. Visualize the box model using browser DevTools.', 152, 3, 'Beginner', 'Understand box model components, Use padding and margin, Apply box-sizing', 35),

('Colors and Typography', 'Colors and fonts define your site visual identity.\n\n## Colors in CSS\n\n```css\n/* Named Colors */\ncolor: red;\n\n/* Hexadecimal */\ncolor: #FF0000;\ncolor: #F00; /* Shorthand */\n\n/* RGB */\ncolor: rgb(255, 0, 0);\n\n/* RGBA with transparency */\ncolor: rgba(255, 0, 0, 0.5);\n\n/* HSL */\ncolor: hsl(0, 100%, 50%);\n```\n\n## Typography\n\n```css\nbody {\n    font-family: Helvetica Neue, Arial, sans-serif;\n    font-size: 16px;\n    font-weight: 400;\n    line-height: 1.6;\n    text-align: left;\n    letter-spacing: 1px;\n}\n```\n\n## Google Fonts\n\n```html\n<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">\n```\n\n## Exercise\nCreate a typography showcase with different fonts, sizes, and colors. Import a Google Font.', 152, 4, 'Beginner', 'Use various color formats, Style typography, Implement Google Fonts', 40);

-- Chapter 4: CSS Layout Techniques (Chapter ID: 153)
INSERT INTO lesson (title, content, chapter_id, sort_order, difficulty, learning_objectives, estimated_time) VALUES 
('Display Property', 'The display property controls element behavior.\n\n## Display Values\n\n```css\n/* Block - Full width, line break */\ndiv { display: block; }\n\n/* Inline - Only needed width */\nspan { display: inline; }\n\n/* Inline-Block - Inline but accepts width/height */\n.button { display: inline-block; }\n\n/* None - Hidden */\n.hidden { display: none; }\n```\n\n## Block vs Inline\n\nBlock: Accepts width/height, creates line break\nInline: No width/height, flows with text\nInline-Block: Best of both worlds\n\n## Common Block Elements\ndiv, p, h1-h6, section, article, header, footer\n\n## Common Inline Elements\nspan, a, strong, em, img\n\n## Exercise\nCreate examples showing the difference between block, inline, and inline-block elements.', 153, 1, 'Intermediate', 'Understand display values, Differentiate block and inline, Use inline-block', 30),

('Flexbox Layout', 'Flexbox is a powerful one-dimensional layout system.\n\n## Flex Container\n\n```css\n.container {\n    display: flex;\n    flex-direction: row; /* or column */\n    justify-content: center; /* Main axis */\n    align-items: center; /* Cross axis */\n    flex-wrap: wrap;\n    gap: 20px;\n}\n```\n\n## Flex Items\n\n```css\n.item {\n    flex-grow: 1; /* Grow to fill space */\n    flex-shrink: 0; /* Do not shrink */\n    flex-basis: 200px; /* Initial size */\n    /* Shorthand */\n    flex: 1 0 200px;\n}\n```\n\n## Justify-Content Values\n\n- flex-start: Items at start\n- flex-end: Items at end\n- center: Items centered\n- space-between: Equal space between\n- space-around: Equal space around\n\n## Exercise\nBuild a navigation bar and a card layout using Flexbox.', 153, 2, 'Intermediate', 'Create flex containers, Align items with justify-content, Control item sizing', 50),

('CSS Grid Layout', 'Grid is a two-dimensional layout system.\n\n## Grid Container\n\n```css\n.grid-container {\n    display: grid;\n    grid-template-columns: repeat(3, 1fr);\n    grid-template-rows: auto;\n    gap: 20px;\n}\n```\n\n## Grid Template Examples\n\n```css\n/* Fixed columns */\ngrid-template-columns: 200px 200px 200px;\n\n/* Flexible columns */\ngrid-template-columns: 1fr 2fr 1fr;\n\n/* Repeat function */\ngrid-template-columns: repeat(4, 1fr);\n\n/* Auto-fill */\ngrid-template-columns: repeat(auto-fill, minmax(250px, 1fr));\n```\n\n## Grid Items\n\n```css\n.item {\n    grid-column: 1 / 3; /* Span 2 columns */\n    grid-row: 1 / 2;\n}\n```\n\n## Exercise\nCreate a complete page layout with header, sidebar, main content, and footer using CSS Grid.', 153, 3, 'Intermediate', 'Create grid layouts, Use grid-template properties, Span items across tracks', 55),

('Position Property', 'Position controls element placement.\n\n## Position Values\n\n```css\n/* Static - Default, normal flow */\n.element { position: static; }\n\n/* Relative - Offset from normal position */\n.relative {\n    position: relative;\n    top: 10px;\n    left: 20px;\n}\n\n/* Absolute - Removed from flow */\n.absolute {\n    position: absolute;\n    top: 0;\n    right: 0;\n}\n\n/* Fixed - Stays in place while scrolling */\n.fixed {\n    position: fixed;\n    bottom: 20px;\n    right: 20px;\n}\n\n/* Sticky - Toggles between relative and fixed */\n.sticky {\n    position: sticky;\n    top: 0;\n}\n```\n\n## Z-Index\n\n```css\n.element {\n    position: relative;\n    z-index: 10; /* Higher = on top */\n}\n```\n\n## Exercise\nCreate a fixed header, a modal overlay, and a sticky sidebar.', 153, 4, 'Intermediate', 'Use position values, Understand positioning context, Control stacking with z-index', 45);

-- Chapter 5: Responsive Web Design (Chapter ID: 154)
INSERT INTO lesson (title, content, chapter_id, sort_order, difficulty, learning_objectives, estimated_time) VALUES 
('Media Queries', 'Media queries apply styles based on device characteristics.\n\n## Basic Syntax\n\n```css\n@media (max-width: 768px) {\n    .container {\n        width: 100%;\n    }\n}\n\n@media (min-width: 769px) and (max-width: 1024px) {\n    .container {\n        width: 80%;\n    }\n}\n```\n\n## Common Breakpoints\n\n```css\n/* Mobile */\n@media (max-width: 576px) { }\n\n/* Tablet */\n@media (min-width: 577px) and (max-width: 768px) { }\n\n/* Laptop */\n@media (min-width: 769px) and (max-width: 1024px) { }\n\n/* Desktop */\n@media (min-width: 1025px) { }\n```\n\n## Mobile-First Approach\n\n```css\n/* Base styles for mobile */\n.container { width: 100%; }\n\n/* Larger screens */\n@media (min-width: 768px) {\n    .container { width: 750px; }\n}\n```\n\n## Exercise\nCreate a responsive layout that changes from single column on mobile to three columns on desktop.', 154, 1, 'Intermediate', 'Write media queries, Define breakpoints, Implement mobile-first design', 40),

('Responsive Images', 'Images must adapt to different screen sizes.\n\n## Fluid Images\n\n```css\nimg {\n    max-width: 100%;\n    height: auto;\n}\n```\n\n## Responsive Image Element\n\n```html\n<picture>\n    <source media="(min-width: 800px)" srcset="large.jpg">\n    <source media="(min-width: 400px)" srcset="medium.jpg">\n    <img src="small.jpg" alt="Responsive image">\n</picture>\n```\n\n## Srcset Attribute\n\n```html\n<img \n    src="default.jpg"\n    srcset="small.jpg 400w,\n            medium.jpg 800w,\n            large.jpg 1200w"\n    sizes="(max-width: 600px) 100vw,\n           (max-width: 1200px) 50vw,\n           33vw"\n    alt="Responsive image">\n```\n\n## Exercise\nImplement responsive images using both srcset and the picture element.', 154, 2, 'Intermediate', 'Create fluid images, Use srcset and sizes, Implement picture element', 35),

('Mobile-First Design', 'Mobile-first is a design philosophy that starts with mobile layouts.\n\n## Why Mobile-First?\n\n- Mobile traffic exceeds desktop\n- Forces focus on essential content\n- Progressive enhancement\n- Better performance\n\n## Mobile-First CSS\n\n```css\n/* Base mobile styles */\nbody {\n    font-size: 16px;\n}\n\n.container {\n    width: 100%;\n    padding: 15px;\n}\n\n/* Tablet */\n@media (min-width: 768px) {\n    .container {\n        width: 750px;\n        margin: 0 auto;\n    }\n}\n\n/* Desktop */\n@media (min-width: 1024px) {\n    .container {\n        width: 960px;\n    }\n}\n```\n\n## Touch-Friendly Design\n\n```css\n.button {\n    min-width: 44px;\n    min-height: 44px;\n    padding: 12px 20px;\n}\n```\n\n## Exercise\nRedesign your portfolio page using mobile-first principles.', 154, 3, 'Intermediate', 'Apply mobile-first methodology, Create touch-friendly interfaces, Use progressive enhancement', 45);

-- Chapter 6: Advanced CSS (Chapter ID: 155)
INSERT INTO lesson (title, content, chapter_id, sort_order, difficulty, learning_objectives, estimated_time) VALUES 
('CSS Transitions and Animations', 'Bring your website to life with smooth animations.\n\n## Transitions\n\n```css\n.button {\n    background: blue;\n    transition: background 0.3s ease, transform 0.3s ease;\n}\n\n.button:hover {\n    background: darkblue;\n    transform: scale(1.05);\n}\n```\n\n## Transition Properties\n\n- transition-property: What to animate\n- transition-duration: How long\n- transition-timing-function: Easing curve\n- transition-delay: Wait before starting\n\n## Keyframe Animations\n\n```css\n@keyframes fadeIn {\n    from {\n        opacity: 0;\n        transform: translateY(20px);\n    }\n    to {\n        opacity: 1;\n        transform: translateY(0);\n    }\n}\n\n.element {\n    animation: fadeIn 0.5s ease forwards;\n}\n```\n\n## Exercise\nCreate a button with hover effects and an animated loading spinner.', 155, 1, 'Advanced', 'Create CSS transitions, Define keyframe animations, Apply animation properties', 50),

('CSS Transforms', 'Transform elements in 2D and 3D space.\n\n## 2D Transforms\n\n```css\n/* Translate (move) */\n.element {\n    transform: translate(50px, 100px);\n    transform: translateX(50px);\n    transform: translateY(100px);\n}\n\n/* Rotate */\n.element {\n    transform: rotate(45deg);\n}\n\n/* Scale */\n.element {\n    transform: scale(1.5);\n    transform: scaleX(2);\n    transform: scaleY(0.5);\n}\n\n/* Skew */\n.element {\n    transform: skew(10deg, 5deg);\n}\n```\n\n## 3D Transforms\n\n```css\n.element {\n    transform: perspective(1000px) rotateY(45deg);\n    transform: rotateX(30deg) rotateZ(15deg);\n}\n```\n\n## Transform Origin\n\n```css\n.element {\n    transform-origin: center center; /* default */\n    transform-origin: top left;\n    transform-origin: 50% 50%;\n}\n```\n\n## Exercise\nCreate a 3D card flip effect and a rotating image gallery.', 155, 2, 'Advanced', 'Apply 2D transforms, Use 3D transforms, Control transform origin', 45),

('CSS Variables (Custom Properties)', 'Create reusable values and dynamic themes.\n\n## Defining Variables\n\n```css\n:root {\n    --primary-color: #3498db;\n    --secondary-color: #2ecc71;\n    --font-main: Roboto, sans-serif;\n    --spacing-unit: 8px;\n    --border-radius: 4px;\n}\n```\n\n## Using Variables\n\n```css\n.button {\n    background: var(--primary-color);\n    font-family: var(--font-main);\n    padding: var(--spacing-unit);\n    border-radius: var(--border-radius);\n}\n```\n\n## Fallback Values\n\n```css\n.element {\n    color: var(--text-color, #333);\n}\n```\n\n## Dynamic Theming\n\n```css\n:root {\n    --bg-color: #ffffff;\n    --text-color: #333333;\n}\n\n[data-theme="dark"] {\n    --bg-color: #1a1a1a;\n    --text-color: #ffffff;\n}\n\nbody {\n    background: var(--bg-color);\n    color: var(--text-color);\n}\n```\n\n## Exercise\nCreate a light/dark theme toggle using CSS variables.', 155, 3, 'Advanced', 'Define CSS variables, Use variables in styles, Implement theming', 40);

-- Chapter 7: Professional Projects (Chapter ID: 156)
INSERT INTO lesson (title, content, chapter_id, sort_order, difficulty, learning_objectives, estimated_time) VALUES 
('Portfolio Website Project', 'Build a professional portfolio website from scratch.\n\n## Project Requirements\n\n1. Hero section with introduction\n2. About me section\n3. Skills showcase\n4. Project gallery\n5. Contact form\n6. Responsive navigation\n\n## HTML Structure\n\n```html\n<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>Your Name - Portfolio</title>\n    <link rel="stylesheet" href="styles.css">\n</head>\n<body>\n    <header class="header">\n        <nav class="nav">...</nav>\n    </header>\n    <main>\n        <section class="hero">...</section>\n        <section class="about">...</section>\n        <section class="skills">...</section>\n        <section class="projects">...</section>\n        <section class="contact">...</section>\n    </main>\n    <footer>...</footer>\n</body>\n</html>\n```\n\n## Key Features\n\n- Smooth scrolling navigation\n- Animated skill bars\n- Responsive project grid\n- Functional contact form\n- Dark/light theme toggle\n\n## Exercise\nBuild your complete portfolio website with all sections.', 156, 1, 'Advanced', 'Plan website structure, Implement all sections, Add interactivity', 120),

('Landing Page Project', 'Create a high-converting landing page.\n\n## Landing Page Elements\n\n1. Compelling headline\n2. Value proposition\n3. Features/benefits\n4. Social proof\n5. Call-to-action (CTA)\n6. Footer\n\n## Hero Section\n\n```css\n.hero {\n    min-height: 100vh;\n    display: flex;\n    align-items: center;\n    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n    color: white;\n}\n\n.hero h1 {\n    font-size: clamp(2rem, 5vw, 4rem);\n    margin-bottom: 1rem;\n}\n\n.cta-button {\n    padding: 15px 40px;\n    font-size: 1.2rem;\n    border-radius: 50px;\n    background: white;\n    color: #667eea;\n    transition: transform 0.3s ease;\n}\n```\n\n## Features Grid\n\n```css\n.features {\n    display: grid;\n    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n    gap: 30px;\n}\n\n.feature-card {\n    padding: 30px;\n    text-align: center;\n    border-radius: 10px;\n    box-shadow: 0 5px 20px rgba(0,0,0,0.1);\n}\n```\n\n## Exercise\nCreate a product landing page with all essential elements.', 156, 2, 'Advanced', 'Design landing page structure, Create compelling CTAs, Implement feature showcase', 90),

('Final Certification Preparation', 'Prepare for your HTML and CSS certification exam.\n\n## Exam Topics\n\n### HTML (40%)\n- Document structure\n- Semantic elements\n- Forms and validation\n- Accessibility\n- SEO best practices\n\n### CSS (50%)\n- Selectors and specificity\n- Box model\n- Flexbox and Grid\n- Responsive design\n- Animations\n\n### Best Practices (10%)\n- Code organization\n- Performance optimization\n- Cross-browser compatibility\n\n## Study Tips\n\n1. Review all lessons\n2. Practice coding daily\n3. Build projects from scratch\n4. Test on multiple browsers\n5. Validate your HTML\n\n## Resources\n\n- MDN Web Docs\n- W3C Validator\n- CSS-Tricks\n- Can I Use\n\n## Exercise\nReview all course materials and take practice quizzes.', 156, 3, 'Advanced', 'Review key concepts, Practice exam questions, Prepare for certification', 60);
