<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260323105428 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE application ADD proposed_budget NUMERIC(10, 2) NOT NULL, ADD timeline VARCHAR(255) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', DROP resume_url, DROP applied_at, CHANGE cover_letter cover_letter LONGTEXT NOT NULL, CHANGE status status VARCHAR(20) NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE applicant_id freelancer_id INT NOT NULL');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1BE04EA9 FOREIGN KEY (job_id) REFERENCES job (id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC18545BDF5 FOREIGN KEY (freelancer_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_A45BDDC1BE04EA9 ON application (job_id)');
        $this->addSql('CREATE INDEX IDX_A45BDDC18545BDF5 ON application (freelancer_id)');
        $this->addSql('DROP INDEX teacher_profile_id ON availability');
        $this->addSql('ALTER TABLE availability ADD teacher_id INT NOT NULL, ADD is_active TINYINT(1) DEFAULT 1 NOT NULL, ADD created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', DROP teacher_profile_id, DROP is_recurring, DROP notes, CHANGE day_of_week day_of_week SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE availability ADD CONSTRAINT FK_3FB7A2BF41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher_profile (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_3FB7A2BF41807E1D ON availability (teacher_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_availability ON availability (teacher_id, day_of_week, start_time)');
        $this->addSql('ALTER TABLE badge CHANGE description description LONGTEXT DEFAULT NULL, CHANGE color color VARCHAR(7) NOT NULL, CHANGE points_required points_required INT NOT NULL, CHANGE category category VARCHAR(20) NOT NULL, CHANGE code code VARCHAR(100) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FEF0481D77153098 ON badge (code)');
        $this->addSql('ALTER TABLE booking DROP INDEX time_slot_id, ADD UNIQUE INDEX UNIQ_E00CEDDED62B0FA (time_slot_id)');
        $this->addSql('DROP INDEX teacher_profile_id ON booking');
        $this->addSql('ALTER TABLE booking DROP teacher_profile_id, DROP notes, DROP confirmed_at, DROP cancelled_at, DROP user_email, DROP phone_number, DROP created_at, CHANGE user_id user_id INT DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT NULL, CHANGE first_name first_name VARCHAR(255) NOT NULL, CHANGE last_name last_name VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE phone phone VARCHAR(255) DEFAULT NULL, CHANGE booked_at booked_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE613FECDF FOREIGN KEY (session_id) REFERENCES session (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEF1FAD9D3 FOREIGN KEY (bundle_id) REFERENCES bundle (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher_profile (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDED62B0FA FOREIGN KEY (time_slot_id) REFERENCES time_slot (id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDE613FECDF ON booking (session_id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDE41807E1D ON booking (teacher_id)');
        $this->addSql('DROP INDEX idx_booking_user ON booking');
        $this->addSql('CREATE INDEX IDX_E00CEDDEA76ED395 ON booking (user_id)');
        $this->addSql('DROP INDEX bundle_id ON booking');
        $this->addSql('CREATE INDEX IDX_E00CEDDEF1FAD9D3 ON booking (bundle_id)');
        $this->addSql('ALTER TABLE bundle ADD teacher_id INT DEFAULT NULL, ADD type VARCHAR(20) NOT NULL, ADD sessions_total INT NOT NULL, ADD sessions_used INT DEFAULT 0 NOT NULL, ADD expires_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD status VARCHAR(20) DEFAULT \'active\' NOT NULL, ADD purchased_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', DROP name, DROP description, DROP discount_percentage, DROP validity_days, DROP is_active, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE session_count student_id INT NOT NULL');
        $this->addSql('ALTER TABLE bundle ADD CONSTRAINT FK_A57B32FDCB944F1A FOREIGN KEY (student_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE bundle ADD CONSTRAINT FK_A57B32FD41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher_profile (id)');
        $this->addSql('CREATE INDEX IDX_A57B32FDCB944F1A ON bundle (student_id)');
        $this->addSql('CREATE INDEX IDX_A57B32FD41807E1D ON bundle (teacher_id)');
        $this->addSql('ALTER TABLE bundle_usage DROP FOREIGN KEY bundle_usage_ibfk_1');
        $this->addSql('ALTER TABLE bundle_usage DROP FOREIGN KEY bundle_usage_ibfk_2');
        $this->addSql('DROP INDEX user_id ON bundle_usage');
        $this->addSql('ALTER TABLE bundle_usage DROP FOREIGN KEY bundle_usage_ibfk_1');
        $this->addSql('ALTER TABLE bundle_usage DROP user_id, DROP sessions_used, DROP sessions_remaining, DROP purchased_at, DROP expires_at, DROP status, CHANGE used_at used_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE booking_id booking_id INT NOT NULL');
        $this->addSql('ALTER TABLE bundle_usage ADD CONSTRAINT FK_4BB3EBDBF1FAD9D3 FOREIGN KEY (bundle_id) REFERENCES bundle (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bundle_usage ADD CONSTRAINT FK_4BB3EBDB3301C60 FOREIGN KEY (booking_id) REFERENCES booking (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4BB3EBDB3301C60 ON bundle_usage (booking_id)');
        $this->addSql('DROP INDEX bundle_id ON bundle_usage');
        $this->addSql('CREATE INDEX IDX_4BB3EBDBF1FAD9D3 ON bundle_usage (bundle_id)');
        $this->addSql('ALTER TABLE bundle_usage ADD CONSTRAINT bundle_usage_ibfk_1 FOREIGN KEY (bundle_id) REFERENCES bundle (id)');
        $this->addSql('ALTER TABLE category DROP image, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE slug slug VARCHAR(255) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('DROP INDEX slug ON category');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C1989D9B62 ON category (slug)');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY certificate_ibfk_3');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY certificate_ibfk_1');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY certificate_ibfk_2');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY certificate_ibfk_3');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY certificate_ibfk_1');
        $this->addSql('ALTER TABLE certificate CHANGE quiz_result_id quiz_result_id INT NOT NULL, CHANGE file_path file_path VARCHAR(500) NOT NULL, CHANGE file_size file_size INT NOT NULL, CHANGE generated_at generated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE is_downloaded is_downloaded TINYINT(1) NOT NULL, CHANGE last_downloaded_at last_downloaded_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE download_count download_count INT NOT NULL');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_219CDA4AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_219CDA4A591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('DROP INDEX user_id ON certificate');
        $this->addSql('CREATE INDEX IDX_219CDA4AA76ED395 ON certificate (user_id)');
        $this->addSql('DROP INDEX quiz_result_id ON certificate');
        $this->addSql('CREATE INDEX IDX_219CDA4A1C7C7A5 ON certificate (quiz_result_id)');
        $this->addSql('DROP INDEX course_id ON certificate');
        $this->addSql('CREATE INDEX IDX_219CDA4A591CC992 ON certificate (course_id)');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT certificate_ibfk_2 FOREIGN KEY (quiz_result_id) REFERENCES quiz_result (id)');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT certificate_ibfk_3 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT certificate_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chapter DROP FOREIGN KEY chapter_ibfk_1');
        $this->addSql('ALTER TABLE chapter DROP created_at, CHANGE sort_order sort_order INT NOT NULL');
        $this->addSql('DROP INDEX course_id ON chapter');
        $this->addSql('CREATE INDEX idx_chapter_course ON chapter (course_id)');
        $this->addSql('ALTER TABLE chapter ADD CONSTRAINT chapter_ibfk_1 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_course_status ON course');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY course_ibfk_1');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY course_ibfk_2');
        $this->addSql('ALTER TABLE course DROP updated_at, CHANGE category_id category_id INT NOT NULL, CHANGE short_description short_description LONGTEXT NOT NULL, CHANGE level level VARCHAR(255) DEFAULT NULL, CHANGE price price NUMERIC(10, 2) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE language language VARCHAR(255) DEFAULT NULL, CHANGE duration duration DOUBLE PRECISION DEFAULT NULL, CHANGE requirements requirements LONGTEXT DEFAULT NULL, CHANGE learning_outcomes learning_outcomes LONGTEXT DEFAULT NULL, CHANGE target_audience target_audience LONGTEXT DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT \'inactive\' NOT NULL, CHANGE image_status image_status VARCHAR(20) DEFAULT \'pending\' NOT NULL, CHANGE video_status video_status VARCHAR(20) DEFAULT \'pending\' NOT NULL, CHANGE image_progress image_progress DOUBLE PRECISION DEFAULT \'0\' NOT NULL, CHANGE video_progress video_progress DOUBLE PRECISION DEFAULT \'0\' NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('DROP INDEX idx_course_category ON course');
        $this->addSql('CREATE INDEX IDX_169E6FB912469DE2 ON course (category_id)');
        $this->addSql('DROP INDEX user_id ON course');
        $this->addSql('CREATE INDEX IDX_169E6FB9A76ED395 ON course (user_id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT course_ibfk_1 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT course_ibfk_2 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE course_test DROP FOREIGN KEY course_test_ibfk_1');
        $this->addSql('ALTER TABLE course_test DROP max_attempts, DROP is_active, CHANGE test_type test_type VARCHAR(20) DEFAULT \'completion\' NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE time_limit time_limit INT NOT NULL, CHANGE passing_score passing_score DOUBLE PRECISION NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('DROP INDEX course_id ON course_test');
        $this->addSql('CREATE INDEX IDX_10DDA30A591CC992 ON course_test (course_id)');
        $this->addSql('ALTER TABLE course_test ADD CONSTRAINT course_test_ibfk_1 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course_test_result DROP FOREIGN KEY course_test_result_ibfk_2');
        $this->addSql('ALTER TABLE course_test_result DROP FOREIGN KEY course_test_result_ibfk_1');
        $this->addSql('ALTER TABLE course_test_result DROP FOREIGN KEY course_test_result_ibfk_2');
        $this->addSql('ALTER TABLE course_test_result DROP FOREIGN KEY course_test_result_ibfk_1');
        $this->addSql('ALTER TABLE course_test_result DROP completed_at, CHANGE score score INT NOT NULL, CHANGE total_questions total_questions INT NOT NULL, CHANGE percentage percentage DOUBLE PRECISION NOT NULL, CHANGE passed passed TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE course_test_result ADD CONSTRAINT FK_F0DDF6E9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE course_test_result ADD CONSTRAINT FK_F0DDF6E9169E01B5 FOREIGN KEY (course_test_id) REFERENCES course_test (id)');
        $this->addSql('DROP INDEX user_id ON course_test_result');
        $this->addSql('CREATE INDEX IDX_F0DDF6E9A76ED395 ON course_test_result (user_id)');
        $this->addSql('DROP INDEX course_test_id ON course_test_result');
        $this->addSql('CREATE INDEX IDX_F0DDF6E9169E01B5 ON course_test_result (course_test_id)');
        $this->addSql('ALTER TABLE course_test_result ADD CONSTRAINT course_test_result_ibfk_2 FOREIGN KEY (course_test_id) REFERENCES course_test (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course_test_result ADD CONSTRAINT course_test_result_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE enrollment CHANGE status status VARCHAR(20) DEFAULT \'active\' NOT NULL, CHANGE progress progress DOUBLE PRECISION DEFAULT \'0\' NOT NULL, CHANGE enrolled_at enrolled_at DATETIME NOT NULL, CHANGE ip_address ip_address VARCHAR(45) DEFAULT NULL, CHANGE user_agent user_agent LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_DBDCD7E1591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_DBDCD7E1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_DBDCD7E1CB7D0048 FOREIGN KEY (starting_lesson_id) REFERENCES lesson (id)');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_DBDCD7E1A2BAD590 FOREIGN KEY (placement_test_result_id) REFERENCES course_test_result (id)');
        $this->addSql('CREATE INDEX IDX_DBDCD7E1CB7D0048 ON enrollment (starting_lesson_id)');
        $this->addSql('CREATE INDEX IDX_DBDCD7E1A2BAD590 ON enrollment (placement_test_result_id)');
        $this->addSql('DROP INDEX idx_enrollment_course ON enrollment');
        $this->addSql('CREATE INDEX IDX_DBDCD7E1591CC992 ON enrollment (course_id)');
        $this->addSql('DROP INDEX idx_enrollment_user ON enrollment');
        $this->addSql('CREATE INDEX IDX_DBDCD7E1A76ED395 ON enrollment (user_id)');
        $this->addSql('ALTER TABLE favorite DROP FOREIGN KEY favorite_ibfk_1');
        $this->addSql('ALTER TABLE favorite DROP FOREIGN KEY favorite_ibfk_2');
        $this->addSql('DROP INDEX user_course ON favorite');
        $this->addSql('DROP INDEX course_id ON favorite');
        $this->addSql('ALTER TABLE favorite CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE course_id job_id INT NOT NULL');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED9BE04EA9 FOREIGN KEY (job_id) REFERENCES job (id)');
        $this->addSql('CREATE INDEX IDX_68C58ED9BE04EA9 ON favorite (job_id)');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY job_ibfk_1');
        $this->addSql('DROP INDEX employer_id ON job');
        $this->addSql('ALTER TABLE job ADD budget DOUBLE PRECISION NOT NULL, ADD deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD type VARCHAR(50) DEFAULT NULL, ADD experience_level VARCHAR(50) DEFAULT NULL, ADD duration VARCHAR(100) DEFAULT NULL, ADD skills VARCHAR(500) DEFAULT NULL, ADD slug VARCHAR(255) NOT NULL, DROP job_type, DROP salary_min, DROP salary_max, DROP salary_type, DROP deadline, DROP updated_at, CHANGE description description LONGTEXT NOT NULL, CHANGE requirements requirements LONGTEXT DEFAULT NULL, CHANGE status status VARCHAR(20) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE employer_id client_id INT NOT NULL');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F819EB6921 FOREIGN KEY (client_id) REFERENCES user (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FBD8E0F8989D9B62 ON job (slug)');
        $this->addSql('CREATE INDEX IDX_FBD8E0F819EB6921 ON job (client_id)');
        $this->addSql('ALTER TABLE lesson DROP created_at, DROP updated_at, CHANGE duration duration VARCHAR(255) NOT NULL, CHANGE type type VARCHAR(50) NOT NULL, CHANGE content content LONGTEXT DEFAULT NULL, CHANGE difficulty difficulty VARCHAR(20) DEFAULT NULL, CHANGE learning_objectives learning_objectives LONGTEXT DEFAULT NULL, CHANGE prerequisites prerequisites LONGTEXT DEFAULT NULL, CHANGE transcript transcript LONGTEXT DEFAULT NULL, CHANGE resources resources LONGTEXT DEFAULT NULL, CHANGE assessment assessment LONGTEXT DEFAULT NULL, CHANGE is_completed is_completed TINYINT(1) DEFAULT 0 NOT NULL, CHANGE views views INT DEFAULT NULL, CHANGE is_preview is_preview TINYINT(1) NOT NULL, CHANGE status status VARCHAR(20) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE sort_order sort_order INT NOT NULL');
        $this->addSql('CREATE INDEX idx_lesson_sort ON lesson (chapter_id, sort_order)');
        $this->addSql('ALTER TABLE lesson_completion DROP FOREIGN KEY lesson_completion_ibfk_1');
        $this->addSql('DROP INDEX user_lesson ON lesson_completion');
        $this->addSql('ALTER TABLE lesson_completion DROP FOREIGN KEY FK_LESSON_COMPLETION_COURSE');
        $this->addSql('ALTER TABLE lesson_completion DROP FOREIGN KEY lesson_completion_ibfk_2');
        $this->addSql('ALTER TABLE lesson_completion DROP time_spent, DROP notes, CHANGE course_id course_id INT NOT NULL, CHANGE completed_at completed_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE lesson_completion ADD CONSTRAINT FK_35DF7EAFA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('DROP INDEX lesson_id ON lesson_completion');
        $this->addSql('CREATE INDEX IDX_35DF7EAFCDF80196 ON lesson_completion (lesson_id)');
        $this->addSql('DROP INDEX idx_lesson_completion_course ON lesson_completion');
        $this->addSql('CREATE INDEX IDX_35DF7EAF591CC992 ON lesson_completion (course_id)');
        $this->addSql('ALTER TABLE lesson_completion ADD CONSTRAINT FK_LESSON_COMPLETION_COURSE FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lesson_completion ADD CONSTRAINT lesson_completion_ibfk_2 FOREIGN KEY (lesson_id) REFERENCES lesson (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification CHANGE email email VARCHAR(255) NOT NULL, CHANGE status status VARCHAR(20) DEFAULT \'active\' NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY order_ibfk_2');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY order_ibfk_1');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY order_ibfk_2');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY order_ibfk_1');
        $this->addSql('ALTER TABLE `order` CHANGE status status VARCHAR(20) NOT NULL, CHANGE review review LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F52993984584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F52993986C755722 FOREIGN KEY (buyer_id) REFERENCES user (id)');
        $this->addSql('DROP INDEX product_id ON `order`');
        $this->addSql('CREATE INDEX IDX_F52993984584665A ON `order` (product_id)');
        $this->addSql('DROP INDEX buyer_id ON `order`');
        $this->addSql('CREATE INDEX IDX_F52993986C755722 ON `order` (buyer_id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT order_ibfk_2 FOREIGN KEY (buyer_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT order_ibfk_1 FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY product_ibfk_2');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY product_ibfk_1');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY product_ibfk_2');
        $this->addSql('ALTER TABLE product CHANGE category_id category_id INT NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE slug slug VARCHAR(255) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE updated_at updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE deleted_at deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD8545BDF5 FOREIGN KEY (freelancer_id) REFERENCES user (id)');
        $this->addSql('DROP INDEX slug ON product');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D34A04AD989D9B62 ON product (slug)');
        $this->addSql('DROP INDEX category_id ON product');
        $this->addSql('CREATE INDEX IDX_D34A04AD12469DE2 ON product (category_id)');
        $this->addSql('DROP INDEX idx_product_freelancer ON product');
        $this->addSql('CREATE INDEX IDX_D34A04AD8545BDF5 ON product (freelancer_id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT product_ibfk_1 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT product_ibfk_2 FOREIGN KEY (freelancer_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE question DROP FOREIGN KEY question_ibfk_1');
        $this->addSql('ALTER TABLE question CHANGE question question VARCHAR(255) NOT NULL, CHANGE option_a option_a VARCHAR(255) NOT NULL, CHANGE option_b option_b VARCHAR(255) NOT NULL, CHANGE option_c option_c VARCHAR(255) NOT NULL, CHANGE option_d option_d VARCHAR(255) NOT NULL, CHANGE correct_option correct_option VARCHAR(1) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE updated_at updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('DROP INDEX quiz_id ON question');
        $this->addSql('CREATE INDEX IDX_B6F7494E853CD175 ON question (quiz_id)');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT question_ibfk_1 FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz DROP FOREIGN KEY quiz_ibfk_2');
        $this->addSql('DROP INDEX lesson_id ON quiz');
        $this->addSql('ALTER TABLE quiz DROP FOREIGN KEY quiz_ibfk_1');
        $this->addSql('ALTER TABLE quiz DROP lesson_id, DROP description, DROP type, DROP time_limit, DROP passing_score, DROP max_attempts, DROP is_active, CHANGE course_id course_id INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE updated_at updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE quiz_type quiz_type VARCHAR(20) NOT NULL');
        $this->addSql('DROP INDEX idx_quiz_course ON quiz');
        $this->addSql('CREATE INDEX IDX_A412FA92591CC992 ON quiz (course_id)');
        $this->addSql('ALTER TABLE quiz ADD CONSTRAINT quiz_ibfk_1 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_result DROP FOREIGN KEY quiz_result_ibfk_2');
        $this->addSql('ALTER TABLE quiz_result DROP FOREIGN KEY quiz_result_ibfk_1');
        $this->addSql('ALTER TABLE quiz_result DROP FOREIGN KEY quiz_result_ibfk_2');
        $this->addSql('ALTER TABLE quiz_result DROP FOREIGN KEY quiz_result_ibfk_1');
        $this->addSql('ALTER TABLE quiz_result DROP total_questions, DROP percentage, DROP passed, DROP answers, DROP completed_at, CHANGE score score INT NOT NULL, CHANGE max_score max_score INT NOT NULL');
        $this->addSql('ALTER TABLE quiz_result ADD CONSTRAINT FK_FE2E314AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE quiz_result ADD CONSTRAINT FK_FE2E314A853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('DROP INDEX user_id ON quiz_result');
        $this->addSql('CREATE INDEX IDX_FE2E314AA76ED395 ON quiz_result (user_id)');
        $this->addSql('DROP INDEX quiz_id ON quiz_result');
        $this->addSql('CREATE INDEX IDX_FE2E314A853CD175 ON quiz_result (quiz_id)');
        $this->addSql('ALTER TABLE quiz_result ADD CONSTRAINT quiz_result_ibfk_2 FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_result ADD CONSTRAINT quiz_result_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_settings DROP INDEX quiz_id, ADD INDEX IDX_33815980853CD175 (quiz_id)');
        $this->addSql('ALTER TABLE quiz_settings DROP FOREIGN KEY quiz_settings_ibfk_1');
        $this->addSql('ALTER TABLE quiz_settings ADD points INT NOT NULL, ADD time_limit INT DEFAULT NULL, ADD passing_score INT NOT NULL, ADD max_attempts INT NOT NULL, DROP show_results, DROP shuffle_questions, DROP show_correct_answers, DROP allow_review, DROP randomize_options, DROP show_timer, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE quiz_settings ADD CONSTRAINT FK_33815980853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY review_ibfk_3');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY review_ibfk_1');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY review_ibfk_4');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY review_ibfk_2');
        $this->addSql('DROP INDEX product_id ON review');
        $this->addSql('DROP INDEX order_id ON review');
        $this->addSql('DROP INDEX reviewer_id ON review');
        $this->addSql('DROP INDEX reviewed_user_id ON review');
        $this->addSql('ALTER TABLE review DROP reviewer_id, DROP reviewed_user_id, DROP product_id, DROP order_id, CHANGE rating rating SMALLINT NOT NULL, CHANGE comment comment LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE tutoring_session_id tutoring_session_id INT NOT NULL, CHANGE student_id student_id INT NOT NULL, CHANGE teacher_id teacher_id INT NOT NULL');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C68B567663 FOREIGN KEY (tutoring_session_id) REFERENCES tutoring_session (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6CB944F1A FOREIGN KEY (student_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C641807E1D FOREIGN KEY (teacher_id) REFERENCES user (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_794381C68B567663 ON review (tutoring_session_id)');
        $this->addSql('CREATE INDEX IDX_794381C6CB944F1A ON review (student_id)');
        $this->addSql('CREATE INDEX IDX_794381C641807E1D ON review (teacher_id)');
        $this->addSql('DROP INDEX session_ibfk_1 ON session');
        $this->addSql('ALTER TABLE session DROP teacher_profile_id, DROP title, DROP description, DROP duration_minutes, DROP price, DROP status, DROP created_at, CHANGE name name VARCHAR(255) NOT NULL, CHANGE level level VARCHAR(255) NOT NULL, CHANGE date date DATETIME NOT NULL, CHANGE start_date start_date DATETIME NOT NULL, CHANGE end_date end_date DATETIME NOT NULL, CHANGE duration duration INT NOT NULL, CHANGE session_description session_description VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D48C4FC193 FOREIGN KEY (instructor_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D412469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('CREATE INDEX IDX_D044D5D48C4FC193 ON session (instructor_id)');
        $this->addSql('CREATE INDEX IDX_D044D5D412469DE2 ON session (category_id)');
        $this->addSql('ALTER TABLE teacher_profile CHANGE subjects subjects JSON NOT NULL COMMENT \'(DC2Type:json)\', CHANGE hourly_rate hourly_rate NUMERIC(10, 2) NOT NULL, CHANGE bio bio LONGTEXT DEFAULT NULL, CHANGE experience_years experience_years INT DEFAULT 0 NOT NULL, CHANGE rating_avg rating_avg NUMERIC(3, 2) NOT NULL, CHANGE review_count review_count INT DEFAULT 0 NOT NULL, CHANGE is_verified is_verified TINYINT(1) DEFAULT 0 NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE teacher_profile ADD CONSTRAINT FK_4C95274EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('DROP INDEX user_id ON teacher_profile');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4C95274EA76ED395 ON teacher_profile (user_id)');
        $this->addSql('DROP INDEX teacher_profile_id ON time_slot');
        $this->addSql('ALTER TABLE time_slot ADD availability_id INT NOT NULL, ADD created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', DROP teacher_profile_id, DROP is_available, CHANGE status status VARCHAR(20) DEFAULT \'available\' NOT NULL');
        $this->addSql('ALTER TABLE time_slot ADD CONSTRAINT FK_1B3294A61778466 FOREIGN KEY (availability_id) REFERENCES availability (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_1B3294A61778466 ON time_slot (availability_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_slot ON time_slot (availability_id, date, start_time)');
        $this->addSql('ALTER TABLE tutoring_session DROP INDEX booking_id, ADD UNIQUE INDEX UNIQ_DD9D67613301C60 (booking_id)');
        $this->addSql('ALTER TABLE tutoring_session DROP FOREIGN KEY tutoring_session_ibfk_2');
        $this->addSql('DROP INDEX teacher_profile_id ON tutoring_session');
        $this->addSql('DROP INDEX student_id ON tutoring_session');
        $this->addSql('ALTER TABLE tutoring_session DROP student_id, DROP teacher_profile_id, DROP duration_minutes, DROP cost, DROP student_rating, DROP student_feedback, CHANGE booking_id booking_id INT NOT NULL, CHANGE started_at started_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE ended_at ended_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE status status VARCHAR(20) DEFAULT \'scheduled\' NOT NULL, CHANGE notes notes LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('DROP INDEX idx_user_email ON user');
        $this->addSql('ALTER TABLE user DROP name, DROP updated_at, CHANGE full_name full_name VARCHAR(100) NOT NULL, CHANGE email email VARCHAR(100) NOT NULL, CHANGE agree_terms agree_terms TINYINT(1) DEFAULT 0 NOT NULL, CHANGE role_id role_id INT DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT \'active\' NOT NULL, CHANGE bio bio LONGTEXT DEFAULT NULL, CHANGE location location VARCHAR(100) DEFAULT NULL, CHANGE face_encoding face_encoding LONGTEXT DEFAULT NULL, CHANGE face_enabled face_enabled TINYINT(1) DEFAULT 0 NOT NULL, CHANGE income income NUMERIC(12, 2) DEFAULT \'0\' NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649D60322AC FOREIGN KEY (role_id) REFERENCES roles (id)');
        $this->addSql('DROP INDEX email ON user');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON user (email)');
        $this->addSql('DROP INDEX role_id ON user');
        $this->addSql('CREATE INDEX IDX_8D93D649D60322AC ON user (role_id)');
        $this->addSql('ALTER TABLE user_badge DROP FOREIGN KEY user_badge_ibfk_1');
        $this->addSql('ALTER TABLE user_badge DROP FOREIGN KEY user_badge_ibfk_2');
        $this->addSql('DROP INDEX user_badge ON user_badge');
        $this->addSql('ALTER TABLE user_badge DROP FOREIGN KEY user_badge_ibfk_2');
        $this->addSql('ALTER TABLE user_badge ADD earned_reason LONGTEXT DEFAULT NULL, ADD progress INT DEFAULT 1 NOT NULL, CHANGE earned_at earned_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345F7A2C2FC FOREIGN KEY (badge_id) REFERENCES badge (id)');
        $this->addSql('DROP INDEX badge_id ON user_badge');
        $this->addSql('CREATE INDEX IDX_1C32B345F7A2C2FC ON user_badge (badge_id)');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT user_badge_ibfk_2 FOREIGN KEY (badge_id) REFERENCES badge (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_points DROP INDEX user_id, ADD INDEX IDX_42E89514A76ED395 (user_id)');
        $this->addSql('ALTER TABLE user_points DROP FOREIGN KEY user_points_ibfk_1');
        $this->addSql('ALTER TABLE user_points DROP learning_points, DROP teaching_points, DROP marketplace_points, DROP social_points, DROP current_level, DROP last_earned_at, CHANGE total_points total_points INT DEFAULT 0 NOT NULL, CHANGE last_updated last_updated DATETIME NOT NULL');
        $this->addSql('ALTER TABLE user_points ADD CONSTRAINT FK_42E89514A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_points ADD CONSTRAINT FK_42E89514C2C9318D FOREIGN KEY (current_level_id) REFERENCES user_level (id)');
        $this->addSql('CREATE INDEX IDX_42E89514C2C9318D ON user_points (current_level_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1BE04EA9');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC18545BDF5');
        $this->addSql('DROP INDEX IDX_A45BDDC1BE04EA9 ON application');
        $this->addSql('DROP INDEX IDX_A45BDDC18545BDF5 ON application');
        $this->addSql('ALTER TABLE application ADD resume_url VARCHAR(255) DEFAULT NULL, ADD applied_at DATETIME DEFAULT CURRENT_TIMESTAMP, DROP proposed_budget, DROP timeline, DROP created_at, DROP deleted_at, CHANGE cover_letter cover_letter TEXT DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT \'pending\', CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE freelancer_id applicant_id INT NOT NULL');
        $this->addSql('ALTER TABLE availability DROP FOREIGN KEY FK_3FB7A2BF41807E1D');
        $this->addSql('DROP INDEX IDX_3FB7A2BF41807E1D ON availability');
        $this->addSql('DROP INDEX unique_availability ON availability');
        $this->addSql('ALTER TABLE availability ADD teacher_profile_id INT DEFAULT NULL, ADD is_recurring TINYINT(1) DEFAULT 1, ADD notes VARCHAR(255) DEFAULT NULL, DROP teacher_id, DROP is_active, DROP created_at, DROP updated_at, CHANGE day_of_week day_of_week INT NOT NULL');
        $this->addSql('CREATE INDEX teacher_profile_id ON availability (teacher_profile_id)');
        $this->addSql('DROP INDEX UNIQ_FEF0481D77153098 ON badge');
        $this->addSql('ALTER TABLE badge CHANGE description description TEXT DEFAULT NULL, CHANGE code code VARCHAR(100) DEFAULT NULL, CHANGE color color VARCHAR(20) DEFAULT NULL, CHANGE category category VARCHAR(50) DEFAULT \'achievement\', CHANGE points_required points_required INT DEFAULT 0');
        $this->addSql('ALTER TABLE booking DROP INDEX UNIQ_E00CEDDED62B0FA, ADD INDEX time_slot_id (time_slot_id)');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDE613FECDF');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDEA76ED395');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDEF1FAD9D3');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDE41807E1D');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDED62B0FA');
        $this->addSql('DROP INDEX IDX_E00CEDDE613FECDF ON booking');
        $this->addSql('DROP INDEX IDX_E00CEDDE41807E1D ON booking');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDEA76ED395');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDEF1FAD9D3');
        $this->addSql('ALTER TABLE booking ADD teacher_profile_id INT DEFAULT NULL, ADD notes TEXT DEFAULT NULL, ADD confirmed_at DATETIME DEFAULT NULL, ADD cancelled_at DATETIME DEFAULT NULL, ADD user_email VARCHAR(255) DEFAULT NULL, ADD phone_number VARCHAR(255) DEFAULT NULL, ADD created_at DATETIME DEFAULT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE first_name first_name VARCHAR(100) DEFAULT NULL, CHANGE last_name last_name VARCHAR(100) DEFAULT NULL, CHANGE email email VARCHAR(180) DEFAULT NULL, CHANGE phone phone VARCHAR(20) DEFAULT NULL, CHANGE booked_at booked_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT \'pending\'');
        $this->addSql('CREATE INDEX teacher_profile_id ON booking (teacher_profile_id)');
        $this->addSql('DROP INDEX idx_e00ceddef1fad9d3 ON booking');
        $this->addSql('CREATE INDEX bundle_id ON booking (bundle_id)');
        $this->addSql('DROP INDEX idx_e00ceddea76ed395 ON booking');
        $this->addSql('CREATE INDEX idx_booking_user ON booking (user_id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEF1FAD9D3 FOREIGN KEY (bundle_id) REFERENCES bundle (id)');
        $this->addSql('ALTER TABLE bundle DROP FOREIGN KEY FK_A57B32FDCB944F1A');
        $this->addSql('ALTER TABLE bundle DROP FOREIGN KEY FK_A57B32FD41807E1D');
        $this->addSql('DROP INDEX IDX_A57B32FDCB944F1A ON bundle');
        $this->addSql('DROP INDEX IDX_A57B32FD41807E1D ON bundle');
        $this->addSql('ALTER TABLE bundle ADD name VARCHAR(255) NOT NULL, ADD description TEXT DEFAULT NULL, ADD session_count INT NOT NULL, ADD discount_percentage NUMERIC(5, 2) DEFAULT \'0.00\', ADD validity_days INT DEFAULT 30, ADD is_active TINYINT(1) DEFAULT 1, DROP student_id, DROP teacher_id, DROP type, DROP sessions_total, DROP sessions_used, DROP expires_at, DROP status, DROP purchased_at, DROP updated_at, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bundle_usage DROP FOREIGN KEY FK_4BB3EBDBF1FAD9D3');
        $this->addSql('ALTER TABLE bundle_usage DROP FOREIGN KEY FK_4BB3EBDB3301C60');
        $this->addSql('DROP INDEX UNIQ_4BB3EBDB3301C60 ON bundle_usage');
        $this->addSql('ALTER TABLE bundle_usage DROP FOREIGN KEY FK_4BB3EBDBF1FAD9D3');
        $this->addSql('ALTER TABLE bundle_usage ADD user_id INT NOT NULL, ADD sessions_used INT DEFAULT 0, ADD sessions_remaining INT NOT NULL, ADD purchased_at DATETIME DEFAULT CURRENT_TIMESTAMP, ADD expires_at DATETIME DEFAULT NULL, ADD status VARCHAR(20) DEFAULT \'active\', CHANGE booking_id booking_id INT DEFAULT NULL, CHANGE used_at used_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE bundle_usage ADD CONSTRAINT bundle_usage_ibfk_1 FOREIGN KEY (bundle_id) REFERENCES bundle (id)');
        $this->addSql('ALTER TABLE bundle_usage ADD CONSTRAINT bundle_usage_ibfk_2 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX user_id ON bundle_usage (user_id)');
        $this->addSql('DROP INDEX idx_4bb3ebdbf1fad9d3 ON bundle_usage');
        $this->addSql('CREATE INDEX bundle_id ON bundle_usage (bundle_id)');
        $this->addSql('ALTER TABLE bundle_usage ADD CONSTRAINT FK_4BB3EBDBF1FAD9D3 FOREIGN KEY (bundle_id) REFERENCES bundle (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category ADD image VARCHAR(255) DEFAULT NULL, CHANGE slug slug VARCHAR(255) DEFAULT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('DROP INDEX uniq_64c19c1989d9b62 ON category');
        $this->addSql('CREATE UNIQUE INDEX slug ON category (slug)');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_219CDA4AA76ED395');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_219CDA4A591CC992');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_219CDA4AA76ED395');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_219CDA4A1C7C7A5');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_219CDA4A591CC992');
        $this->addSql('ALTER TABLE certificate CHANGE quiz_result_id quiz_result_id INT DEFAULT NULL, CHANGE file_path file_path VARCHAR(255) NOT NULL, CHANGE file_size file_size INT DEFAULT NULL, CHANGE generated_at generated_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE is_downloaded is_downloaded TINYINT(1) DEFAULT 0, CHANGE last_downloaded_at last_downloaded_at DATETIME DEFAULT NULL, CHANGE download_count download_count INT DEFAULT 0');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT certificate_ibfk_3 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT certificate_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_219cda4aa76ed395 ON certificate');
        $this->addSql('CREATE INDEX user_id ON certificate (user_id)');
        $this->addSql('DROP INDEX idx_219cda4a1c7c7a5 ON certificate');
        $this->addSql('CREATE INDEX quiz_result_id ON certificate (quiz_result_id)');
        $this->addSql('DROP INDEX idx_219cda4a591cc992 ON certificate');
        $this->addSql('CREATE INDEX course_id ON certificate (course_id)');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_219CDA4AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_219CDA4A1C7C7A5 FOREIGN KEY (quiz_result_id) REFERENCES quiz_result (id)');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_219CDA4A591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE chapter DROP FOREIGN KEY FK_F981B52E591CC992');
        $this->addSql('ALTER TABLE chapter ADD created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE sort_order sort_order INT DEFAULT 0');
        $this->addSql('DROP INDEX idx_chapter_course ON chapter');
        $this->addSql('CREATE INDEX course_id ON chapter (course_id)');
        $this->addSql('ALTER TABLE chapter ADD CONSTRAINT FK_F981B52E591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB912469DE2');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB9A76ED395');
        $this->addSql('ALTER TABLE course ADD updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE category_id category_id INT DEFAULT NULL, CHANGE short_description short_description TEXT DEFAULT NULL, CHANGE level level VARCHAR(50) DEFAULT \'beginner\', CHANGE price price NUMERIC(10, 2) DEFAULT \'0.00\', CHANGE description description TEXT DEFAULT NULL, CHANGE language language VARCHAR(50) DEFAULT \'English\', CHANGE duration duration DOUBLE PRECISION DEFAULT \'0\', CHANGE requirements requirements TEXT DEFAULT NULL, CHANGE learning_outcomes learning_outcomes TEXT DEFAULT NULL, CHANGE target_audience target_audience TEXT DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT \'draft\', CHANGE image_status image_status VARCHAR(20) DEFAULT \'none\', CHANGE video_status video_status VARCHAR(20) DEFAULT \'none\', CHANGE image_progress image_progress DOUBLE PRECISION DEFAULT \'0\', CHANGE video_progress video_progress DOUBLE PRECISION DEFAULT \'0\', CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('CREATE INDEX idx_course_status ON course (status)');
        $this->addSql('DROP INDEX idx_169e6fb912469de2 ON course');
        $this->addSql('CREATE INDEX idx_course_category ON course (category_id)');
        $this->addSql('DROP INDEX idx_169e6fb9a76ed395 ON course');
        $this->addSql('CREATE INDEX user_id ON course (user_id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB912469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE course_test DROP FOREIGN KEY FK_10DDA30A591CC992');
        $this->addSql('ALTER TABLE course_test ADD max_attempts INT DEFAULT 3, ADD is_active TINYINT(1) DEFAULT 1, CHANGE description description TEXT DEFAULT NULL, CHANGE time_limit time_limit INT DEFAULT 30, CHANGE passing_score passing_score INT DEFAULT 70, CHANGE test_type test_type VARCHAR(50) DEFAULT \'placement\', CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('DROP INDEX idx_10dda30a591cc992 ON course_test');
        $this->addSql('CREATE INDEX course_id ON course_test (course_id)');
        $this->addSql('ALTER TABLE course_test ADD CONSTRAINT FK_10DDA30A591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course_test_result DROP FOREIGN KEY FK_F0DDF6E9A76ED395');
        $this->addSql('ALTER TABLE course_test_result DROP FOREIGN KEY FK_F0DDF6E9169E01B5');
        $this->addSql('ALTER TABLE course_test_result DROP FOREIGN KEY FK_F0DDF6E9A76ED395');
        $this->addSql('ALTER TABLE course_test_result DROP FOREIGN KEY FK_F0DDF6E9169E01B5');
        $this->addSql('ALTER TABLE course_test_result ADD completed_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE score score INT DEFAULT 0, CHANGE total_questions total_questions INT DEFAULT 0, CHANGE percentage percentage DOUBLE PRECISION DEFAULT \'0\', CHANGE passed passed TINYINT(1) DEFAULT 0');
        $this->addSql('ALTER TABLE course_test_result ADD CONSTRAINT course_test_result_ibfk_2 FOREIGN KEY (course_test_id) REFERENCES course_test (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course_test_result ADD CONSTRAINT course_test_result_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_f0ddf6e9169e01b5 ON course_test_result');
        $this->addSql('CREATE INDEX course_test_id ON course_test_result (course_test_id)');
        $this->addSql('DROP INDEX idx_f0ddf6e9a76ed395 ON course_test_result');
        $this->addSql('CREATE INDEX user_id ON course_test_result (user_id)');
        $this->addSql('ALTER TABLE course_test_result ADD CONSTRAINT FK_F0DDF6E9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE course_test_result ADD CONSTRAINT FK_F0DDF6E9169E01B5 FOREIGN KEY (course_test_id) REFERENCES course_test (id)');
        $this->addSql('ALTER TABLE enrollment DROP FOREIGN KEY FK_DBDCD7E1591CC992');
        $this->addSql('ALTER TABLE enrollment DROP FOREIGN KEY FK_DBDCD7E1A76ED395');
        $this->addSql('ALTER TABLE enrollment DROP FOREIGN KEY FK_DBDCD7E1CB7D0048');
        $this->addSql('ALTER TABLE enrollment DROP FOREIGN KEY FK_DBDCD7E1A2BAD590');
        $this->addSql('DROP INDEX IDX_DBDCD7E1CB7D0048 ON enrollment');
        $this->addSql('DROP INDEX IDX_DBDCD7E1A2BAD590 ON enrollment');
        $this->addSql('ALTER TABLE enrollment DROP FOREIGN KEY FK_DBDCD7E1591CC992');
        $this->addSql('ALTER TABLE enrollment DROP FOREIGN KEY FK_DBDCD7E1A76ED395');
        $this->addSql('ALTER TABLE enrollment CHANGE enrolled_at enrolled_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE status status VARCHAR(20) DEFAULT \'active\', CHANGE progress progress DOUBLE PRECISION DEFAULT \'0\', CHANGE ip_address ip_address VARCHAR(45) NOT NULL COMMENT \'Student IP address at time of enrollment\', CHANGE user_agent user_agent LONGTEXT NOT NULL COMMENT \'Student browser user agent at time of enrollment\'');
        $this->addSql('DROP INDEX idx_dbdcd7e1a76ed395 ON enrollment');
        $this->addSql('CREATE INDEX idx_enrollment_user ON enrollment (user_id)');
        $this->addSql('DROP INDEX idx_dbdcd7e1591cc992 ON enrollment');
        $this->addSql('CREATE INDEX idx_enrollment_course ON enrollment (course_id)');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_DBDCD7E1591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_DBDCD7E1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE favorite DROP FOREIGN KEY FK_68C58ED9A76ED395');
        $this->addSql('ALTER TABLE favorite DROP FOREIGN KEY FK_68C58ED9BE04EA9');
        $this->addSql('DROP INDEX IDX_68C58ED9BE04EA9 ON favorite');
        $this->addSql('ALTER TABLE favorite CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE job_id course_id INT NOT NULL');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT favorite_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT favorite_ibfk_2 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX user_course ON favorite (user_id, course_id)');
        $this->addSql('CREATE INDEX course_id ON favorite (course_id)');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_FBD8E0F819EB6921');
        $this->addSql('DROP INDEX UNIQ_FBD8E0F8989D9B62 ON job');
        $this->addSql('DROP INDEX IDX_FBD8E0F819EB6921 ON job');
        $this->addSql('ALTER TABLE job ADD job_type VARCHAR(50) DEFAULT \'full-time\', ADD salary_min NUMERIC(10, 2) DEFAULT NULL, ADD salary_max NUMERIC(10, 2) DEFAULT NULL, ADD salary_type VARCHAR(20) DEFAULT \'yearly\', ADD deadline DATETIME DEFAULT NULL, ADD updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, DROP budget, DROP deleted_at, DROP type, DROP experience_level, DROP duration, DROP skills, DROP slug, CHANGE description description TEXT DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT \'open\', CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE requirements requirements TEXT DEFAULT NULL, CHANGE client_id employer_id INT NOT NULL');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT job_ibfk_1 FOREIGN KEY (employer_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX employer_id ON job (employer_id)');
        $this->addSql('DROP INDEX idx_lesson_sort ON lesson');
        $this->addSql('ALTER TABLE lesson ADD created_at DATETIME DEFAULT CURRENT_TIMESTAMP, ADD updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE duration duration VARCHAR(50) DEFAULT NULL, CHANGE type type VARCHAR(50) DEFAULT \'video\', CHANGE content content TEXT DEFAULT NULL, CHANGE difficulty difficulty VARCHAR(50) DEFAULT \'beginner\', CHANGE learning_objectives learning_objectives TEXT DEFAULT NULL, CHANGE prerequisites prerequisites TEXT DEFAULT NULL, CHANGE transcript transcript TEXT DEFAULT NULL, CHANGE resources resources TEXT DEFAULT NULL, CHANGE assessment assessment TEXT DEFAULT NULL, CHANGE is_completed is_completed TINYINT(1) DEFAULT 0, CHANGE views views INT DEFAULT 0, CHANGE is_preview is_preview TINYINT(1) DEFAULT 0, CHANGE status status VARCHAR(20) DEFAULT \'draft\', CHANGE description description TEXT DEFAULT NULL, CHANGE sort_order sort_order INT DEFAULT 0');
        $this->addSql('ALTER TABLE lesson_completion DROP FOREIGN KEY FK_35DF7EAFA76ED395');
        $this->addSql('ALTER TABLE lesson_completion DROP FOREIGN KEY FK_35DF7EAFCDF80196');
        $this->addSql('ALTER TABLE lesson_completion DROP FOREIGN KEY FK_35DF7EAF591CC992');
        $this->addSql('ALTER TABLE lesson_completion ADD time_spent INT DEFAULT 0, ADD notes TEXT DEFAULT NULL, CHANGE course_id course_id INT DEFAULT NULL, CHANGE completed_at completed_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE lesson_completion ADD CONSTRAINT lesson_completion_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX user_lesson ON lesson_completion (user_id, lesson_id)');
        $this->addSql('DROP INDEX idx_35df7eaf591cc992 ON lesson_completion');
        $this->addSql('CREATE INDEX IDX_LESSON_COMPLETION_COURSE ON lesson_completion (course_id)');
        $this->addSql('DROP INDEX idx_35df7eafcdf80196 ON lesson_completion');
        $this->addSql('CREATE INDEX lesson_id ON lesson_completion (lesson_id)');
        $this->addSql('ALTER TABLE lesson_completion ADD CONSTRAINT FK_35DF7EAFCDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lesson_completion ADD CONSTRAINT FK_35DF7EAF591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification CHANGE email email VARCHAR(180) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE status status VARCHAR(20) DEFAULT \'active\'');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F52993984584665A');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F52993986C755722');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F52993984584665A');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F52993986C755722');
        $this->addSql('ALTER TABLE `order` CHANGE status status VARCHAR(20) DEFAULT \'pending\', CHANGE review review TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT order_ibfk_2 FOREIGN KEY (buyer_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT order_ibfk_1 FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_f52993984584665a ON `order`');
        $this->addSql('CREATE INDEX product_id ON `order` (product_id)');
        $this->addSql('DROP INDEX idx_f52993986c755722 ON `order`');
        $this->addSql('CREATE INDEX buyer_id ON `order` (buyer_id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F52993984584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F52993986C755722 FOREIGN KEY (buyer_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD8545BDF5');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD12469DE2');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD8545BDF5');
        $this->addSql('ALTER TABLE product CHANGE category_id category_id INT DEFAULT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE slug slug VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT product_ibfk_2 FOREIGN KEY (freelancer_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_d34a04ad12469de2 ON product');
        $this->addSql('CREATE INDEX category_id ON product (category_id)');
        $this->addSql('DROP INDEX idx_d34a04ad8545bdf5 ON product');
        $this->addSql('CREATE INDEX idx_product_freelancer ON product (freelancer_id)');
        $this->addSql('DROP INDEX uniq_d34a04ad989d9b62 ON product');
        $this->addSql('CREATE UNIQUE INDEX slug ON product (slug)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD12469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD8545BDF5 FOREIGN KEY (freelancer_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE question DROP FOREIGN KEY FK_B6F7494E853CD175');
        $this->addSql('ALTER TABLE question CHANGE question question TEXT NOT NULL, CHANGE option_a option_a VARCHAR(500) NOT NULL, CHANGE option_b option_b VARCHAR(500) NOT NULL, CHANGE option_c option_c VARCHAR(500) DEFAULT NULL, CHANGE option_d option_d VARCHAR(500) DEFAULT NULL, CHANGE correct_option correct_option CHAR(1) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('DROP INDEX idx_b6f7494e853cd175 ON question');
        $this->addSql('CREATE INDEX quiz_id ON question (quiz_id)');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494E853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz DROP FOREIGN KEY FK_A412FA92591CC992');
        $this->addSql('ALTER TABLE quiz ADD lesson_id INT DEFAULT NULL, ADD description TEXT DEFAULT NULL, ADD type VARCHAR(50) DEFAULT \'lesson\', ADD time_limit INT DEFAULT 30, ADD passing_score INT DEFAULT 70, ADD max_attempts INT DEFAULT 3, ADD is_active TINYINT(1) DEFAULT 1, CHANGE course_id course_id INT DEFAULT NULL, CHANGE quiz_type quiz_type VARCHAR(20) DEFAULT \'lesson\' NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE quiz ADD CONSTRAINT quiz_ibfk_2 FOREIGN KEY (lesson_id) REFERENCES lesson (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX lesson_id ON quiz (lesson_id)');
        $this->addSql('DROP INDEX idx_a412fa92591cc992 ON quiz');
        $this->addSql('CREATE INDEX idx_quiz_course ON quiz (course_id)');
        $this->addSql('ALTER TABLE quiz ADD CONSTRAINT FK_A412FA92591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_result DROP FOREIGN KEY FK_FE2E314AA76ED395');
        $this->addSql('ALTER TABLE quiz_result DROP FOREIGN KEY FK_FE2E314A853CD175');
        $this->addSql('ALTER TABLE quiz_result DROP FOREIGN KEY FK_FE2E314AA76ED395');
        $this->addSql('ALTER TABLE quiz_result DROP FOREIGN KEY FK_FE2E314A853CD175');
        $this->addSql('ALTER TABLE quiz_result ADD total_questions INT DEFAULT 0, ADD percentage DOUBLE PRECISION DEFAULT \'0\', ADD passed TINYINT(1) DEFAULT 0, ADD answers JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', ADD completed_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE score score INT DEFAULT 0, CHANGE max_score max_score INT DEFAULT 100 NOT NULL');
        $this->addSql('ALTER TABLE quiz_result ADD CONSTRAINT quiz_result_ibfk_2 FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_result ADD CONSTRAINT quiz_result_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_fe2e314aa76ed395 ON quiz_result');
        $this->addSql('CREATE INDEX user_id ON quiz_result (user_id)');
        $this->addSql('DROP INDEX idx_fe2e314a853cd175 ON quiz_result');
        $this->addSql('CREATE INDEX quiz_id ON quiz_result (quiz_id)');
        $this->addSql('ALTER TABLE quiz_result ADD CONSTRAINT FK_FE2E314AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE quiz_result ADD CONSTRAINT FK_FE2E314A853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('ALTER TABLE quiz_settings DROP INDEX IDX_33815980853CD175, ADD UNIQUE INDEX quiz_id (quiz_id)');
        $this->addSql('ALTER TABLE quiz_settings DROP FOREIGN KEY FK_33815980853CD175');
        $this->addSql('ALTER TABLE quiz_settings ADD show_results TINYINT(1) DEFAULT 1, ADD shuffle_questions TINYINT(1) DEFAULT 0, ADD show_correct_answers TINYINT(1) DEFAULT 1, ADD allow_review TINYINT(1) DEFAULT 1, ADD randomize_options TINYINT(1) DEFAULT 0, ADD show_timer TINYINT(1) DEFAULT 1, DROP points, DROP time_limit, DROP passing_score, DROP max_attempts, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE quiz_settings ADD CONSTRAINT quiz_settings_ibfk_1 FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C68B567663');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6CB944F1A');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C641807E1D');
        $this->addSql('DROP INDEX UNIQ_794381C68B567663 ON review');
        $this->addSql('DROP INDEX IDX_794381C6CB944F1A ON review');
        $this->addSql('DROP INDEX IDX_794381C641807E1D ON review');
        $this->addSql('ALTER TABLE review ADD reviewer_id INT NOT NULL, ADD reviewed_user_id INT DEFAULT NULL, ADD product_id INT DEFAULT NULL, ADD order_id INT DEFAULT NULL, CHANGE tutoring_session_id tutoring_session_id INT DEFAULT NULL, CHANGE student_id student_id INT DEFAULT NULL, CHANGE teacher_id teacher_id INT DEFAULT NULL, CHANGE rating rating INT NOT NULL, CHANGE comment comment TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT review_ibfk_3 FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT review_ibfk_1 FOREIGN KEY (reviewer_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT review_ibfk_4 FOREIGN KEY (order_id) REFERENCES `order` (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT review_ibfk_2 FOREIGN KEY (reviewed_user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX product_id ON review (product_id)');
        $this->addSql('CREATE INDEX order_id ON review (order_id)');
        $this->addSql('CREATE INDEX reviewer_id ON review (reviewer_id)');
        $this->addSql('CREATE INDEX reviewed_user_id ON review (reviewed_user_id)');
        $this->addSql('ALTER TABLE session DROP FOREIGN KEY FK_D044D5D48C4FC193');
        $this->addSql('ALTER TABLE session DROP FOREIGN KEY FK_D044D5D412469DE2');
        $this->addSql('DROP INDEX IDX_D044D5D48C4FC193 ON session');
        $this->addSql('DROP INDEX IDX_D044D5D412469DE2 ON session');
        $this->addSql('ALTER TABLE session ADD teacher_profile_id INT DEFAULT NULL, ADD title VARCHAR(255) DEFAULT NULL, ADD description TEXT DEFAULT NULL, ADD duration_minutes INT DEFAULT 60, ADD price NUMERIC(10, 2) DEFAULT NULL, ADD status VARCHAR(20) DEFAULT \'active\', ADD created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE level level VARCHAR(255) DEFAULT NULL, CHANGE date date DATETIME DEFAULT NULL, CHANGE start_date start_date DATETIME DEFAULT NULL, CHANGE end_date end_date DATETIME DEFAULT NULL, CHANGE duration duration INT DEFAULT NULL, CHANGE session_description session_description VARCHAR(255) DEFAULT NULL');
        $this->addSql('CREATE INDEX session_ibfk_1 ON session (teacher_profile_id)');
        $this->addSql('ALTER TABLE teacher_profile DROP FOREIGN KEY FK_4C95274EA76ED395');
        $this->addSql('ALTER TABLE teacher_profile DROP FOREIGN KEY FK_4C95274EA76ED395');
        $this->addSql('ALTER TABLE teacher_profile CHANGE subjects subjects JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE hourly_rate hourly_rate NUMERIC(10, 2) DEFAULT NULL, CHANGE bio bio TEXT DEFAULT NULL, CHANGE experience_years experience_years INT DEFAULT 0, CHANGE rating_avg rating_avg NUMERIC(3, 2) DEFAULT \'0.00\', CHANGE review_count review_count INT DEFAULT 0, CHANGE is_verified is_verified TINYINT(1) DEFAULT 0, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('DROP INDEX uniq_4c95274ea76ed395 ON teacher_profile');
        $this->addSql('CREATE UNIQUE INDEX user_id ON teacher_profile (user_id)');
        $this->addSql('ALTER TABLE teacher_profile ADD CONSTRAINT FK_4C95274EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE time_slot DROP FOREIGN KEY FK_1B3294A61778466');
        $this->addSql('DROP INDEX IDX_1B3294A61778466 ON time_slot');
        $this->addSql('DROP INDEX unique_slot ON time_slot');
        $this->addSql('ALTER TABLE time_slot ADD teacher_profile_id INT DEFAULT NULL, ADD is_available TINYINT(1) DEFAULT 1, DROP availability_id, DROP created_at, CHANGE status status VARCHAR(20) DEFAULT \'available\'');
        $this->addSql('CREATE INDEX teacher_profile_id ON time_slot (teacher_profile_id)');
        $this->addSql('ALTER TABLE tutoring_session DROP INDEX UNIQ_DD9D67613301C60, ADD INDEX booking_id (booking_id)');
        $this->addSql('ALTER TABLE tutoring_session ADD student_id INT NOT NULL, ADD teacher_profile_id INT DEFAULT NULL, ADD duration_minutes INT DEFAULT 0, ADD cost NUMERIC(10, 2) DEFAULT NULL, ADD student_rating INT DEFAULT NULL, ADD student_feedback TEXT DEFAULT NULL, CHANGE booking_id booking_id INT DEFAULT NULL, CHANGE started_at started_at DATETIME DEFAULT NULL, CHANGE ended_at ended_at DATETIME DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT \'scheduled\', CHANGE notes notes TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE tutoring_session ADD CONSTRAINT tutoring_session_ibfk_2 FOREIGN KEY (student_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX teacher_profile_id ON tutoring_session (teacher_profile_id)');
        $this->addSql('CREATE INDEX student_id ON tutoring_session (student_id)');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649D60322AC');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649D60322AC');
        $this->addSql('ALTER TABLE user ADD name VARCHAR(100) DEFAULT NULL, ADD updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE role_id role_id INT DEFAULT 3, CHANGE full_name full_name VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(180) NOT NULL, CHANGE agree_terms agree_terms TINYINT(1) DEFAULT 0, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE status status VARCHAR(20) DEFAULT \'active\', CHANGE bio bio TEXT DEFAULT NULL, CHANGE location location VARCHAR(255) DEFAULT NULL, CHANGE face_encoding face_encoding TEXT DEFAULT NULL, CHANGE face_enabled face_enabled TINYINT(1) DEFAULT 0, CHANGE income income NUMERIC(10, 2) DEFAULT \'0.00\'');
        $this->addSql('CREATE INDEX idx_user_email ON user (email)');
        $this->addSql('DROP INDEX idx_8d93d649d60322ac ON user');
        $this->addSql('CREATE INDEX role_id ON user (role_id)');
        $this->addSql('DROP INDEX uniq_8d93d649e7927c74 ON user');
        $this->addSql('CREATE UNIQUE INDEX email ON user (email)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649D60322AC FOREIGN KEY (role_id) REFERENCES roles (id)');
        $this->addSql('ALTER TABLE user_badge DROP FOREIGN KEY FK_1C32B345A76ED395');
        $this->addSql('ALTER TABLE user_badge DROP FOREIGN KEY FK_1C32B345F7A2C2FC');
        $this->addSql('ALTER TABLE user_badge DROP FOREIGN KEY FK_1C32B345F7A2C2FC');
        $this->addSql('ALTER TABLE user_badge DROP earned_reason, DROP progress, CHANGE earned_at earned_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT user_badge_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT user_badge_ibfk_2 FOREIGN KEY (badge_id) REFERENCES badge (id) ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX user_badge ON user_badge (user_id, badge_id)');
        $this->addSql('DROP INDEX idx_1c32b345f7a2c2fc ON user_badge');
        $this->addSql('CREATE INDEX badge_id ON user_badge (badge_id)');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345F7A2C2FC FOREIGN KEY (badge_id) REFERENCES badge (id)');
        $this->addSql('ALTER TABLE user_points DROP INDEX IDX_42E89514A76ED395, ADD UNIQUE INDEX user_id (user_id)');
        $this->addSql('ALTER TABLE user_points DROP FOREIGN KEY FK_42E89514A76ED395');
        $this->addSql('ALTER TABLE user_points DROP FOREIGN KEY FK_42E89514C2C9318D');
        $this->addSql('DROP INDEX IDX_42E89514C2C9318D ON user_points');
        $this->addSql('ALTER TABLE user_points ADD learning_points INT DEFAULT 0, ADD teaching_points INT DEFAULT 0, ADD marketplace_points INT DEFAULT 0, ADD social_points INT DEFAULT 0, ADD current_level INT DEFAULT 1, ADD last_earned_at DATETIME DEFAULT NULL, CHANGE total_points total_points INT DEFAULT 0, CHANGE last_updated last_updated DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE user_points ADD CONSTRAINT user_points_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
    }
}
