<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260316073629 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_USER_ROLE');
        $this->addSql('CREATE TABLE availability (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', teacher_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', day_of_week SMALLINT NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_3FB7A2BF41807E1D (teacher_id), UNIQUE INDEX unique_availability (teacher_id, day_of_week, start_time), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE badge (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, code VARCHAR(100) NOT NULL, icon VARCHAR(255) DEFAULT NULL, color VARCHAR(7) NOT NULL, category VARCHAR(20) NOT NULL, points_required INT NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, badge_order INT DEFAULT 0 NOT NULL, UNIQUE INDEX UNIQ_FEF0481D77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE booking (id INT AUTO_INCREMENT NOT NULL, session_id INT DEFAULT NULL, user_id INT DEFAULT NULL, bundle_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', teacher_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', time_slot_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, user_email VARCHAR(255) NOT NULL, phone_number VARCHAR(255) DEFAULT NULL, preferred_date DATE DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', status VARCHAR(20) DEFAULT NULL, start_time TIME DEFAULT NULL, duration_minutes INT DEFAULT NULL, total_price NUMERIC(10, 2) DEFAULT NULL, INDEX IDX_E00CEDDE613FECDF (session_id), INDEX IDX_E00CEDDEA76ED395 (user_id), INDEX IDX_E00CEDDEF1FAD9D3 (bundle_id), INDEX IDX_E00CEDDE41807E1D (teacher_id), UNIQUE INDEX UNIQ_E00CEDDED62B0FA (time_slot_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bundle (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', student_id INT NOT NULL, teacher_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', type VARCHAR(20) NOT NULL, sessions_total INT NOT NULL, sessions_used INT DEFAULT 0 NOT NULL, price NUMERIC(10, 2) NOT NULL, expires_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', status VARCHAR(20) DEFAULT \'active\' NOT NULL, purchased_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_A57B32FDCB944F1A (student_id), INDEX IDX_A57B32FD41807E1D (teacher_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bundle_usage (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', bundle_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', booking_id INT NOT NULL, used_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_4BB3EBDBF1FAD9D3 (bundle_id), UNIQUE INDEX UNIQ_4BB3EBDB3301C60 (booking_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE course_category (id INT AUTO_INCREMENT NOT NULL, course_id INT NOT NULL, category_id INT NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_AFF87497591CC992 (course_id), INDEX IDX_AFF8749712469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE course_test (id INT AUTO_INCREMENT NOT NULL, course_id INT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, time_limit INT NOT NULL, passing_score DOUBLE PRECISION NOT NULL, test_type VARCHAR(20) DEFAULT \'completion\' NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_10DDA30A591CC992 (course_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE course_test_question (id INT AUTO_INCREMENT NOT NULL, course_test_id INT NOT NULL, question LONGTEXT NOT NULL, options JSON NOT NULL COMMENT \'(DC2Type:json)\', correct_answer VARCHAR(255) NOT NULL, explanation VARCHAR(255) DEFAULT NULL, difficulty VARCHAR(20) NOT NULL, points INT NOT NULL, INDEX IDX_E01906C1169E01B5 (course_test_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE course_test_result (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, course_test_id INT NOT NULL, score INT NOT NULL, total_questions INT NOT NULL, percentage DOUBLE PRECISION NOT NULL, passed TINYINT(1) NOT NULL, time_taken DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', answers JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_F0DDF6E9A76ED395 (user_id), INDEX IDX_F0DDF6E9169E01B5 (course_test_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE learning_roadmap (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, learning_goal VARCHAR(255) NOT NULL, skill_level VARCHAR(50) NOT NULL, time_commitment VARCHAR(50) DEFAULT NULL, learning_styles JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', roadmap_content JSON NOT NULL COMMENT \'(DC2Type:json)\', generated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_A7645600A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lesson_completion (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, lesson_id INT NOT NULL, course_id INT NOT NULL, completed_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_35DF7EAFA76ED395 (user_id), INDEX IDX_35DF7EAFCDF80196 (lesson_id), INDEX IDX_35DF7EAF591CC992 (course_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE meeting_feedback (id INT AUTO_INCREMENT NOT NULL, booking_id INT NOT NULL, user_id INT NOT NULL, satisfaction_rating INT NOT NULL, call_quality_rating INT NOT NULL, learning_style_rating INT NOT NULL, comments LONGTEXT DEFAULT NULL, user_role VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_41B8698D3301C60 (booking_id), INDEX IDX_41B8698DA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE permissions (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, category VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE quiz_statistics (id INT AUTO_INCREMENT NOT NULL, quiz_id INT NOT NULL, student_id INT NOT NULL, score INT NOT NULL, total_questions INT NOT NULL, correct_answers INT NOT NULL, completed_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', average_time_per_question DOUBLE PRECISION NOT NULL, question_results JSON NOT NULL COMMENT \'(DC2Type:json)\', difficulty_level INT NOT NULL, INDEX IDX_ABBCAC1E853CD175 (quiz_id), INDEX IDX_ABBCAC1ECB944F1A (student_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE review (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', tutoring_session_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', student_id INT NOT NULL, teacher_id INT NOT NULL, rating SMALLINT NOT NULL, comment LONGTEXT DEFAULT NULL, is_public TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_794381C68B567663 (tutoring_session_id), INDEX IDX_794381C6CB944F1A (student_id), INDEX IDX_794381C641807E1D (teacher_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE role_permissions (role_id INT NOT NULL, permission_id INT NOT NULL, INDEX IDX_1FBA94E6D60322AC (role_id), INDEX IDX_1FBA94E6FED90CCA (permission_id), PRIMARY KEY(role_id, permission_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teacher_profile (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', user_id INT NOT NULL, subjects JSON NOT NULL COMMENT \'(DC2Type:json)\', hourly_rate NUMERIC(10, 2) NOT NULL, bio LONGTEXT DEFAULT NULL, education VARCHAR(255) DEFAULT NULL, experience_years INT DEFAULT 0 NOT NULL, rating_avg NUMERIC(3, 2) NOT NULL, review_count INT DEFAULT 0 NOT NULL, is_verified TINYINT(1) DEFAULT 0 NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_4C95274EA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE time_slot (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', availability_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', date DATE NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL, status VARCHAR(20) DEFAULT \'available\' NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_1B3294A61778466 (availability_id), UNIQUE INDEX unique_slot (availability_id, date, start_time), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tutoring_session (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', booking_id INT NOT NULL, started_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ended_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', actual_duration INT DEFAULT 0 NOT NULL, status VARCHAR(20) DEFAULT \'scheduled\' NOT NULL, notes LONGTEXT DEFAULT NULL, recording_url VARCHAR(500) DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_DD9D67613301C60 (booking_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_badge (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, badge_id INT NOT NULL, earned_at DATETIME NOT NULL, earned_reason LONGTEXT DEFAULT NULL, progress INT DEFAULT 1 NOT NULL, INDEX IDX_1C32B345A76ED395 (user_id), INDEX IDX_1C32B345F7A2C2FC (badge_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_level (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, code VARCHAR(50) NOT NULL, min_xp INT NOT NULL, max_xp INT NOT NULL, color VARCHAR(7) NOT NULL, icon VARCHAR(100) DEFAULT NULL, level_order INT NOT NULL, UNIQUE INDEX UNIQ_7828374B77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_points (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, current_level_id INT DEFAULT NULL, total_points INT DEFAULT 0 NOT NULL, current_level_points INT DEFAULT 0 NOT NULL, last_updated DATETIME NOT NULL, rank_position INT DEFAULT 0 NOT NULL, INDEX IDX_42E89514A76ED395 (user_id), INDEX IDX_42E89514C2C9318D (current_level_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE availability ADD CONSTRAINT FK_3FB7A2BF41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher_profile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE613FECDF FOREIGN KEY (session_id) REFERENCES session (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEF1FAD9D3 FOREIGN KEY (bundle_id) REFERENCES bundle (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher_profile (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDED62B0FA FOREIGN KEY (time_slot_id) REFERENCES time_slot (id)');
        $this->addSql('ALTER TABLE bundle ADD CONSTRAINT FK_A57B32FDCB944F1A FOREIGN KEY (student_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE bundle ADD CONSTRAINT FK_A57B32FD41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher_profile (id)');
        $this->addSql('ALTER TABLE bundle_usage ADD CONSTRAINT FK_4BB3EBDBF1FAD9D3 FOREIGN KEY (bundle_id) REFERENCES bundle (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bundle_usage ADD CONSTRAINT FK_4BB3EBDB3301C60 FOREIGN KEY (booking_id) REFERENCES booking (id)');
        $this->addSql('ALTER TABLE course_category ADD CONSTRAINT FK_AFF87497591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE course_category ADD CONSTRAINT FK_AFF8749712469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE course_test ADD CONSTRAINT FK_10DDA30A591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course_test_question ADD CONSTRAINT FK_E01906C1169E01B5 FOREIGN KEY (course_test_id) REFERENCES course_test (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course_test_result ADD CONSTRAINT FK_F0DDF6E9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE course_test_result ADD CONSTRAINT FK_F0DDF6E9169E01B5 FOREIGN KEY (course_test_id) REFERENCES course_test (id)');
        $this->addSql('ALTER TABLE learning_roadmap ADD CONSTRAINT FK_A7645600A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE lesson_completion ADD CONSTRAINT FK_35DF7EAFA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE lesson_completion ADD CONSTRAINT FK_35DF7EAFCDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lesson_completion ADD CONSTRAINT FK_35DF7EAF591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE meeting_feedback ADD CONSTRAINT FK_41B8698D3301C60 FOREIGN KEY (booking_id) REFERENCES booking (id)');
        $this->addSql('ALTER TABLE meeting_feedback ADD CONSTRAINT FK_41B8698DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE quiz_statistics ADD CONSTRAINT FK_ABBCAC1E853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('ALTER TABLE quiz_statistics ADD CONSTRAINT FK_ABBCAC1ECB944F1A FOREIGN KEY (student_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C68B567663 FOREIGN KEY (tutoring_session_id) REFERENCES tutoring_session (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6CB944F1A FOREIGN KEY (student_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C641807E1D FOREIGN KEY (teacher_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6D60322AC FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6FED90CCA FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE teacher_profile ADD CONSTRAINT FK_4C95274EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE time_slot ADD CONSTRAINT FK_1B3294A61778466 FOREIGN KEY (availability_id) REFERENCES availability (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tutoring_session ADD CONSTRAINT FK_DD9D67613301C60 FOREIGN KEY (booking_id) REFERENCES booking (id)');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345F7A2C2FC FOREIGN KEY (badge_id) REFERENCES badge (id)');
        $this->addSql('ALTER TABLE user_points ADD CONSTRAINT FK_42E89514A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_points ADD CONSTRAINT FK_42E89514C2C9318D FOREIGN KEY (current_level_id) REFERENCES user_level (id)');
        $this->addSql('ALTER TABLE lesson_progress DROP FOREIGN KEY FK_PROGRESS_LESSON');
        $this->addSql('ALTER TABLE lesson_progress DROP FOREIGN KEY FK_PROGRESS_STUDENT');
        $this->addSql('ALTER TABLE quiz_attempt_answer DROP FOREIGN KEY FK_ATTEMPT_ANSWER_QUESTION');
        $this->addSql('ALTER TABLE quiz_attempt_answer DROP FOREIGN KEY FK_ATTEMPT_ANSWER_SELECTED');
        $this->addSql('ALTER TABLE quiz_attempt_answer DROP FOREIGN KEY FK_ATTEMPT_ANSWER_ATTEMPT');
        $this->addSql('ALTER TABLE student DROP FOREIGN KEY FK_STUDENT_USER');
        $this->addSql('ALTER TABLE trust_score DROP FOREIGN KEY FK_TRUST_SELLER');
        $this->addSql('ALTER TABLE validation_result DROP FOREIGN KEY FK_VALIDATION_PRODUCT');
        $this->addSql('ALTER TABLE validation_result DROP FOREIGN KEY FK_VALIDATION_SELLER');
        $this->addSql('DROP TABLE lesson_progress');
        $this->addSql('DROP TABLE quiz_attempt_answer');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE trust_score');
        $this->addSql('DROP TABLE validation_result');
        $this->addSql('DROP INDEX IDX_APPLICATION_STATUS ON application');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_APPLICATION_FREELANCER');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_APPLICATION_JOB');
        $this->addSql('DROP INDEX idx_application_job ON application');
        $this->addSql('CREATE INDEX IDX_A45BDDC1BE04EA9 ON application (job_id)');
        $this->addSql('DROP INDEX idx_application_freelancer ON application');
        $this->addSql('CREATE INDEX IDX_A45BDDC18545BDF5 ON application (freelancer_id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_APPLICATION_FREELANCER FOREIGN KEY (freelancer_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_APPLICATION_JOB FOREIGN KEY (job_id) REFERENCES job (id)');
        $this->addSql('DROP INDEX UNIQ_CATEGORY_NAME ON category');
        $this->addSql('ALTER TABLE category CHANGE name name VARCHAR(255) NOT NULL');
        $this->addSql('DROP INDEX uniq_category_slug ON category');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C1989D9B62 ON category (slug)');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_CERTIFICATE_QUIZ');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_CERTIFICATE_STUDENT');
        $this->addSql('DROP INDEX IDX_CERTIFICATE_QUIZ ON certificate');
        $this->addSql('DROP INDEX UNIQ_CERTIFICATE_CODE ON certificate');
        $this->addSql('DROP INDEX IDX_CERTIFICATE_STUDENT ON certificate');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_CERTIFICATE_COURSE');
        $this->addSql('ALTER TABLE certificate ADD quiz_result_id INT NOT NULL, ADD filename VARCHAR(255) NOT NULL, ADD file_path VARCHAR(500) NOT NULL, ADD file_size INT NOT NULL, ADD is_downloaded TINYINT(1) NOT NULL, ADD last_downloaded_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD download_count INT NOT NULL, DROP quiz_id, DROP verification_code, DROP pdf_file, CHANGE course_id course_id INT NOT NULL, CHANGE student_id user_id INT NOT NULL, CHANGE issued_at generated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_219CDA4AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_219CDA4A1C7C7A5 FOREIGN KEY (quiz_result_id) REFERENCES quiz_result (id)');
        $this->addSql('CREATE INDEX IDX_219CDA4AA76ED395 ON certificate (user_id)');
        $this->addSql('CREATE INDEX IDX_219CDA4A1C7C7A5 ON certificate (quiz_result_id)');
        $this->addSql('DROP INDEX idx_certificate_course ON certificate');
        $this->addSql('CREATE INDEX IDX_219CDA4A591CC992 ON certificate (course_id)');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_CERTIFICATE_COURSE FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE chapter DROP position, DROP created_at, CHANGE sort_order sort_order INT NOT NULL');
        $this->addSql('ALTER TABLE checkout DROP FOREIGN KEY FK_CHECKOUT_USER');
        $this->addSql('DROP INDEX IDX_CHECKOUT_USER ON checkout');
        $this->addSql('ALTER TABLE checkout ADD first_name VARCHAR(100) NOT NULL, ADD last_name VARCHAR(100) NOT NULL, ADD email VARCHAR(255) NOT NULL, ADD phone VARCHAR(20) DEFAULT NULL, ADD address VARCHAR(255) NOT NULL, ADD city VARCHAR(100) NOT NULL, ADD state VARCHAR(100) NOT NULL, ADD zip_code VARCHAR(20) NOT NULL, ADD country VARCHAR(100) NOT NULL, ADD card_number VARCHAR(50) NOT NULL, ADD expiry_date VARCHAR(10) NOT NULL, ADD cvv VARCHAR(5) NOT NULL, ADD cardholder_name VARCHAR(100) NOT NULL, ADD agree_terms TINYINT(1) NOT NULL, DROP user_id, DROP transaction_id, CHANGE total_amount total_amount NUMERIC(10, 2) NOT NULL, CHANGE status status VARCHAR(20) DEFAULT \'pending\' NOT NULL, CHANGE payment_method payment_method VARCHAR(20) DEFAULT \'credit_card\' NOT NULL');
        $this->addSql('ALTER TABLE contact ADD first_name VARCHAR(100) NOT NULL, ADD last_name VARCHAR(100) NOT NULL, ADD phone VARCHAR(20) DEFAULT NULL, DROP name, CHANGE subject subject VARCHAR(100) NOT NULL, CHANGE status status VARCHAR(20) DEFAULT \'pending\' NOT NULL');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_COURSE_USER');
        $this->addSql('DROP INDEX IDX_COURSE_STATUS ON course');
        $this->addSql('DROP INDEX UNIQ_COURSE_SLUG ON course');
        $this->addSql('DROP INDEX IDX_COURSE_PUBLISHED ON course');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_COURSE_USER');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_COURSE_CATEGORY');
        $this->addSql('ALTER TABLE course DROP slug, DROP is_published, DROP updated_at, DROP deleted_at, CHANGE price price NUMERIC(10, 2) NOT NULL, CHANGE level level VARCHAR(255) DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT \'inactive\' NOT NULL, CHANGE image_status image_status VARCHAR(20) DEFAULT \'pending\' NOT NULL, CHANGE video_status video_status VARCHAR(20) DEFAULT \'pending\' NOT NULL, CHANGE image_progress image_progress DOUBLE PRECISION DEFAULT \'0\' NOT NULL, CHANGE video_progress video_progress DOUBLE PRECISION DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('DROP INDEX idx_course_category ON course');
        $this->addSql('CREATE INDEX IDX_169E6FB912469DE2 ON course (category_id)');
        $this->addSql('DROP INDEX idx_course_user ON course');
        $this->addSql('CREATE INDEX IDX_169E6FB9A76ED395 ON course (user_id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_COURSE_USER FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_COURSE_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE course_lesson DROP FOREIGN KEY FK_COURSE_LESSON_COURSE');
        $this->addSql('ALTER TABLE course_lesson DROP FOREIGN KEY FK_COURSE_LESSON_LESSON');
        $this->addSql('ALTER TABLE course_lesson DROP FOREIGN KEY FK_COURSE_LESSON_COURSE');
        $this->addSql('ALTER TABLE course_lesson DROP FOREIGN KEY FK_COURSE_LESSON_LESSON');
        $this->addSql('ALTER TABLE course_lesson ADD created_at DATETIME NOT NULL, DROP title, DROP content, CHANGE lesson_id lesson_id INT NOT NULL, CHANGE position sort_order INT NOT NULL');
        $this->addSql('ALTER TABLE course_lesson ADD CONSTRAINT FK_564CB5BE591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE course_lesson ADD CONSTRAINT FK_564CB5BECDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id)');
        $this->addSql('DROP INDEX idx_course_lesson_course ON course_lesson');
        $this->addSql('CREATE INDEX IDX_564CB5BE591CC992 ON course_lesson (course_id)');
        $this->addSql('DROP INDEX idx_course_lesson_lesson ON course_lesson');
        $this->addSql('CREATE INDEX IDX_564CB5BECDF80196 ON course_lesson (lesson_id)');
        $this->addSql('ALTER TABLE course_lesson ADD CONSTRAINT FK_COURSE_LESSON_COURSE FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course_lesson ADD CONSTRAINT FK_COURSE_LESSON_LESSON FOREIGN KEY (lesson_id) REFERENCES lesson (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE course_review DROP FOREIGN KEY FK_REVIEW_STUDENT');
        $this->addSql('DROP INDEX IDX_REVIEW_STUDENT ON course_review');
        $this->addSql('ALTER TABLE course_review DROP FOREIGN KEY FK_REVIEW_COURSE');
        $this->addSql('ALTER TABLE course_review CHANGE created_at created_at DATETIME NOT NULL, CHANGE student_id user_id INT NOT NULL');
        $this->addSql('ALTER TABLE course_review ADD CONSTRAINT FK_D77B408BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_D77B408BA76ED395 ON course_review (user_id)');
        $this->addSql('DROP INDEX idx_review_course ON course_review');
        $this->addSql('CREATE INDEX IDX_D77B408B591CC992 ON course_review (course_id)');
        $this->addSql('ALTER TABLE course_review ADD CONSTRAINT FK_REVIEW_COURSE FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE enrollment DROP FOREIGN KEY FK_ENROLLMENT_STUDENT');
        $this->addSql('DROP INDEX IDX_ENROLLMENT_STUDENT ON enrollment');
        $this->addSql('ALTER TABLE enrollment DROP FOREIGN KEY FK_ENROLLMENT_COURSE');
        $this->addSql('ALTER TABLE enrollment ADD placement_test_result_id INT DEFAULT NULL, ADD ip_address VARCHAR(45) DEFAULT NULL, ADD user_agent LONGTEXT DEFAULT NULL, DROP student_id, CHANGE enrolled_at enrolled_at DATETIME NOT NULL, CHANGE status status VARCHAR(20) DEFAULT \'active\' NOT NULL, CHANGE progress progress DOUBLE PRECISION DEFAULT \'0\' NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE progress_percent starting_lesson_id INT DEFAULT NULL, CHANGE is_completed placement_test_taken TINYINT(1) DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_DBDCD7E1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_DBDCD7E1CB7D0048 FOREIGN KEY (starting_lesson_id) REFERENCES lesson (id)');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_DBDCD7E1A2BAD590 FOREIGN KEY (placement_test_result_id) REFERENCES course_test_result (id)');
        $this->addSql('CREATE INDEX IDX_DBDCD7E1A76ED395 ON enrollment (user_id)');
        $this->addSql('CREATE INDEX IDX_DBDCD7E1CB7D0048 ON enrollment (starting_lesson_id)');
        $this->addSql('CREATE INDEX IDX_DBDCD7E1A2BAD590 ON enrollment (placement_test_result_id)');
        $this->addSql('DROP INDEX idx_enrollment_course ON enrollment');
        $this->addSql('CREATE INDEX IDX_DBDCD7E1591CC992 ON enrollment (course_id)');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_ENROLLMENT_COURSE FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE favorite DROP FOREIGN KEY FK_FAVORITE_USER');
        $this->addSql('ALTER TABLE favorite DROP FOREIGN KEY FK_FAVORITE_JOB');
        $this->addSql('DROP INDEX idx_favorite_user ON favorite');
        $this->addSql('CREATE INDEX IDX_68C58ED9A76ED395 ON favorite (user_id)');
        $this->addSql('DROP INDEX idx_favorite_job ON favorite');
        $this->addSql('CREATE INDEX IDX_68C58ED9BE04EA9 ON favorite (job_id)');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_FAVORITE_USER FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_FAVORITE_JOB FOREIGN KEY (job_id) REFERENCES job (id)');
        $this->addSql('DROP INDEX IDX_JOB_STATUS ON job');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_JOB_CLIENT');
        $this->addSql('ALTER TABLE job ADD location VARCHAR(255) DEFAULT NULL, ADD type VARCHAR(50) DEFAULT NULL, ADD experience_level VARCHAR(50) DEFAULT NULL, ADD duration VARCHAR(100) DEFAULT NULL, ADD requirements LONGTEXT DEFAULT NULL, ADD skills VARCHAR(500) DEFAULT NULL, ADD slug VARCHAR(255) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FBD8E0F8989D9B62 ON job (slug)');
        $this->addSql('DROP INDEX idx_job_client ON job');
        $this->addSql('CREATE INDEX IDX_FBD8E0F819EB6921 ON job (client_id)');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_JOB_CLIENT FOREIGN KEY (client_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE lesson ADD type VARCHAR(50) NOT NULL, ADD attachment_url VARCHAR(255) DEFAULT NULL, ADD difficulty VARCHAR(20) DEFAULT NULL, ADD learning_objectives LONGTEXT DEFAULT NULL, ADD prerequisites LONGTEXT DEFAULT NULL, ADD materials JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', ADD estimated_time INT DEFAULT NULL, ADD transcript LONGTEXT DEFAULT NULL, ADD thumbnail_url VARCHAR(255) DEFAULT NULL, ADD resources LONGTEXT DEFAULT NULL, ADD assessment LONGTEXT DEFAULT NULL, ADD is_completed TINYINT(1) DEFAULT 0 NOT NULL, ADD views INT DEFAULT NULL, ADD published_at DATETIME DEFAULT NULL, ADD status VARCHAR(20) NOT NULL, ADD description LONGTEXT DEFAULT NULL, ADD sort_order INT NOT NULL, DROP position, DROP created_at, CHANGE duration duration VARCHAR(255) NOT NULL, CHANGE is_preview is_preview TINYINT(1) NOT NULL');
        $this->addSql('CREATE INDEX idx_lesson_sort ON lesson (chapter_id, sort_order)');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_NOTIFICATION_USER');
        $this->addSql('DROP INDEX IDX_NOTIFICATION_USER ON notification');
        $this->addSql('ALTER TABLE notification ADD status VARCHAR(20) DEFAULT \'active\' NOT NULL, DROP user_id, DROP type, DROP message, DROP is_read, CHANGE title email VARCHAR(255) NOT NULL');
        $this->addSql('DROP INDEX IDX_ORDER_STATUS ON `order`');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_ORDER_BUYER');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_ORDER_PRODUCT');
        $this->addSql('ALTER TABLE `order` CHANGE total_price total_price NUMERIC(10, 2) NOT NULL');
        $this->addSql('DROP INDEX idx_order_product ON `order`');
        $this->addSql('CREATE INDEX IDX_F52993984584665A ON `order` (product_id)');
        $this->addSql('DROP INDEX idx_order_buyer ON `order`');
        $this->addSql('CREATE INDEX IDX_F52993986C755722 ON `order` (buyer_id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_ORDER_BUYER FOREIGN KEY (buyer_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('DROP INDEX IDX_PRODUCT_CATEGORY ON product');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_PRODUCT_FREELANCER');
        $this->addSql('ALTER TABLE product ADD category_id INT NOT NULL, DROP category, CHANGE price price NUMERIC(10, 2) NOT NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD12469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('CREATE INDEX IDX_D34A04AD12469DE2 ON product (category_id)');
        $this->addSql('DROP INDEX uniq_product_slug ON product');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D34A04AD989D9B62 ON product (slug)');
        $this->addSql('DROP INDEX idx_product_freelancer ON product');
        $this->addSql('CREATE INDEX IDX_D34A04AD8545BDF5 ON product (freelancer_id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_PRODUCT_FREELANCER FOREIGN KEY (freelancer_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE question DROP FOREIGN KEY FK_QUESTION_QUIZ_LEGACY');
        $this->addSql('ALTER TABLE question DROP FOREIGN KEY FK_QUESTION_QUIZ_LEGACY');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494E853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_question_quiz_legacy ON question');
        $this->addSql('CREATE INDEX IDX_B6F7494E853CD175 ON question (quiz_id)');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_QUESTION_QUIZ_LEGACY FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('ALTER TABLE quiz DROP FOREIGN KEY FK_QUIZ_COURSE');
        $this->addSql('DROP INDEX UNIQ_QUIZ_SLUG ON quiz');
        $this->addSql('ALTER TABLE quiz DROP FOREIGN KEY FK_QUIZ_COURSE');
        $this->addSql('ALTER TABLE quiz ADD quiz_type VARCHAR(20) NOT NULL, DROP slug, DROP time_limit_minutes, DROP is_published, CHANGE course_id course_id INT NOT NULL');
        $this->addSql('ALTER TABLE quiz ADD CONSTRAINT FK_A412FA92591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_quiz_course ON quiz');
        $this->addSql('CREATE INDEX IDX_A412FA92591CC992 ON quiz (course_id)');
        $this->addSql('ALTER TABLE quiz ADD CONSTRAINT FK_QUIZ_COURSE FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE quiz_answer DROP FOREIGN KEY FK_ANSWER_QUESTION');
        $this->addSql('ALTER TABLE quiz_answer DROP FOREIGN KEY FK_ANSWER_QUESTION');
        $this->addSql('ALTER TABLE quiz_answer ADD quiz_result_id INT NOT NULL, ADD answer LONGTEXT NOT NULL, ADD created_at DATETIME NOT NULL, DROP content, CHANGE is_correct is_correct TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE quiz_answer ADD CONSTRAINT FK_3799BA7C1E27F6BF FOREIGN KEY (question_id) REFERENCES quiz_question (id)');
        $this->addSql('ALTER TABLE quiz_answer ADD CONSTRAINT FK_3799BA7C1C7C7A5 FOREIGN KEY (quiz_result_id) REFERENCES quiz_result (id)');
        $this->addSql('CREATE INDEX IDX_3799BA7C1C7C7A5 ON quiz_answer (quiz_result_id)');
        $this->addSql('DROP INDEX idx_answer_question ON quiz_answer');
        $this->addSql('CREATE INDEX IDX_3799BA7C1E27F6BF ON quiz_answer (question_id)');
        $this->addSql('ALTER TABLE quiz_answer ADD CONSTRAINT FK_ANSWER_QUESTION FOREIGN KEY (question_id) REFERENCES quiz_question (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_attempt DROP FOREIGN KEY FK_ATTEMPT_STUDENT');
        $this->addSql('DROP INDEX IDX_ATTEMPT_STUDENT ON quiz_attempt');
        $this->addSql('ALTER TABLE quiz_attempt DROP FOREIGN KEY FK_ATTEMPT_QUIZ');
        $this->addSql('ALTER TABLE quiz_attempt ADD total_questions INT NOT NULL, ADD correct_answers INT NOT NULL, ADD completed_at DATETIME DEFAULT NULL, ADD status VARCHAR(20) DEFAULT \'in_progress\' NOT NULL, DROP finished_at, DROP max_score, CHANGE started_at started_at DATETIME NOT NULL, CHANGE score score DOUBLE PRECISION NOT NULL, CHANGE student_id user_id INT NOT NULL');
        $this->addSql('ALTER TABLE quiz_attempt ADD CONSTRAINT FK_AB6AFC6A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_AB6AFC6A76ED395 ON quiz_attempt (user_id)');
        $this->addSql('DROP INDEX idx_attempt_quiz ON quiz_attempt');
        $this->addSql('CREATE INDEX IDX_AB6AFC6853CD175 ON quiz_attempt (quiz_id)');
        $this->addSql('ALTER TABLE quiz_attempt ADD CONSTRAINT FK_ATTEMPT_QUIZ FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('ALTER TABLE quiz_question DROP FOREIGN KEY FK_QUESTION_QUIZ');
        $this->addSql('ALTER TABLE quiz_question DROP FOREIGN KEY FK_QUESTION_QUIZ');
        $this->addSql('ALTER TABLE quiz_question ADD explanation LONGTEXT DEFAULT NULL, ADD options JSON NOT NULL COMMENT \'(DC2Type:json)\', ADD points INT NOT NULL, ADD created_at DATETIME NOT NULL, CHANGE content question LONGTEXT NOT NULL, CHANGE position correct_answer INT NOT NULL');
        $this->addSql('ALTER TABLE quiz_question ADD CONSTRAINT FK_6033B00B853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('DROP INDEX idx_question_quiz ON quiz_question');
        $this->addSql('CREATE INDEX IDX_6033B00B853CD175 ON quiz_question (quiz_id)');
        $this->addSql('ALTER TABLE quiz_question ADD CONSTRAINT FK_QUESTION_QUIZ FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_result DROP FOREIGN KEY FK_RESULT_QUIZ');
        $this->addSql('ALTER TABLE quiz_result DROP FOREIGN KEY FK_RESULT_USER');
        $this->addSql('DROP INDEX idx_result_user ON quiz_result');
        $this->addSql('CREATE INDEX IDX_FE2E314AA76ED395 ON quiz_result (user_id)');
        $this->addSql('DROP INDEX idx_result_quiz ON quiz_result');
        $this->addSql('CREATE INDEX IDX_FE2E314A853CD175 ON quiz_result (quiz_id)');
        $this->addSql('ALTER TABLE quiz_result ADD CONSTRAINT FK_RESULT_QUIZ FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('ALTER TABLE quiz_result ADD CONSTRAINT FK_RESULT_USER FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE quiz_settings ADD quiz_id INT NOT NULL, ADD points INT NOT NULL, DROP show_answers, DROP shuffle_questions, CHANGE time_limit time_limit INT DEFAULT NULL, CHANGE passing_score passing_score INT NOT NULL, CHANGE max_attempts max_attempts INT NOT NULL');
        $this->addSql('ALTER TABLE quiz_settings ADD CONSTRAINT FK_33815980853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('CREATE INDEX IDX_33815980853CD175 ON quiz_settings (quiz_id)');
        $this->addSql('ALTER TABLE roles ADD description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE session DROP FOREIGN KEY FK_SESSION_INSTRUCTOR');
        $this->addSql('ALTER TABLE session ADD category_id INT DEFAULT NULL, ADD level VARCHAR(255) NOT NULL, ADD date DATETIME NOT NULL, ADD start_date DATETIME NOT NULL, ADD end_date DATETIME NOT NULL, ADD duration INT NOT NULL, ADD session_description VARCHAR(255) NOT NULL, ADD available_from TIME DEFAULT NULL, ADD available_to TIME DEFAULT NULL, ADD hourly_price NUMERIC(10, 2) DEFAULT NULL, DROP description, DROP start_time, DROP end_time, DROP max_participants, DROP price, DROP status, DROP created_at, CHANGE instructor_id instructor_id INT DEFAULT NULL, CHANGE title name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D412469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('CREATE INDEX IDX_D044D5D412469DE2 ON session (category_id)');
        $this->addSql('DROP INDEX idx_session_instructor ON session');
        $this->addSql('CREATE INDEX IDX_D044D5D48C4FC193 ON session (instructor_id)');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_SESSION_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_USER_ROLE');
        $this->addSql('ALTER TABLE user ADD google_id VARCHAR(255) DEFAULT NULL, ADD facebook_id VARCHAR(255) DEFAULT NULL, ADD reset_token VARCHAR(255) DEFAULT NULL, ADD reset_token_expires_at DATETIME DEFAULT NULL, ADD face_encoding LONGTEXT DEFAULT NULL, ADD face_enabled TINYINT(1) DEFAULT 0 NOT NULL, ADD income NUMERIC(12, 2) DEFAULT \'0\' NOT NULL, DROP name, DROP avatar, DROP address, DROP email_verified, DROP updated_at, CHANGE full_name full_name VARCHAR(100) NOT NULL, CHANGE email email VARCHAR(100) NOT NULL, CHANGE agree_terms agree_terms TINYINT(1) DEFAULT 0 NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649D60322AC FOREIGN KEY (role_id) REFERENCES roles (id)');
        $this->addSql('DROP INDEX uniq_user_email ON user');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON user (email)');
        $this->addSql('DROP INDEX idx_user_role ON user');
        $this->addSql('CREATE INDEX IDX_8D93D649D60322AC ON user (role_id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_USER_ROLE FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE SET NULL');
        $this->addSql('DROP INDEX IDX_MESSENGER_QUEUE ON messenger_messages');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE enrollment DROP FOREIGN KEY FK_DBDCD7E1A2BAD590');
        $this->addSql('CREATE TABLE lesson_progress (id INT AUTO_INCREMENT NOT NULL, student_id INT NOT NULL, lesson_id INT NOT NULL, completed_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_PROGRESS_STUDENT (student_id), INDEX IDX_PROGRESS_LESSON (lesson_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE quiz_attempt_answer (id INT AUTO_INCREMENT NOT NULL, attempt_id INT NOT NULL, question_id INT NOT NULL, selected_answer_id INT DEFAULT NULL, INDEX IDX_ATTEMPT_ANSWER_SELECTED (selected_answer_id), INDEX IDX_ATTEMPT_ANSWER_ATTEMPT (attempt_id), INDEX IDX_ATTEMPT_ANSWER_QUESTION (question_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE role (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_ROLE_NAME (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE student (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, full_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, bio LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, skills JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', rating DOUBLE PRECISION DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_STUDENT_USER (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE trust_score (id INT AUTO_INCREMENT NOT NULL, seller_id INT NOT NULL, overall_score DOUBLE PRECISION NOT NULL, behavior_score DOUBLE PRECISION NOT NULL, content_score DOUBLE PRECISION NOT NULL, pricing_score DOUBLE PRECISION NOT NULL, reputation_score DOUBLE PRECISION NOT NULL, score_breakdown JSON NOT NULL COMMENT \'(DC2Type:json)\', historical_trend JSON NOT NULL COMMENT \'(DC2Type:json)\', last_updated DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', risk_level VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX UNIQ_TRUST_SELLER (seller_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE validation_result (id INT AUTO_INCREMENT NOT NULL, seller_id INT NOT NULL, product_id INT DEFAULT NULL, validation_type VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, overall_score DOUBLE PRECISION NOT NULL, risk_level VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, component_scores JSON NOT NULL COMMENT \'(DC2Type:json)\', findings JSON NOT NULL COMMENT \'(DC2Type:json)\', improvement_suggestions JSON NOT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', passed TINYINT(1) NOT NULL, INDEX IDX_VALIDATION_SELLER (seller_id), INDEX IDX_VALIDATION_PRODUCT (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE lesson_progress ADD CONSTRAINT FK_PROGRESS_LESSON FOREIGN KEY (lesson_id) REFERENCES course_lesson (id)');
        $this->addSql('ALTER TABLE lesson_progress ADD CONSTRAINT FK_PROGRESS_STUDENT FOREIGN KEY (student_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE quiz_attempt_answer ADD CONSTRAINT FK_ATTEMPT_ANSWER_QUESTION FOREIGN KEY (question_id) REFERENCES quiz_question (id)');
        $this->addSql('ALTER TABLE quiz_attempt_answer ADD CONSTRAINT FK_ATTEMPT_ANSWER_SELECTED FOREIGN KEY (selected_answer_id) REFERENCES quiz_answer (id)');
        $this->addSql('ALTER TABLE quiz_attempt_answer ADD CONSTRAINT FK_ATTEMPT_ANSWER_ATTEMPT FOREIGN KEY (attempt_id) REFERENCES quiz_attempt (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_STUDENT_USER FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE trust_score ADD CONSTRAINT FK_TRUST_SELLER FOREIGN KEY (seller_id) REFERENCES student (id)');
        $this->addSql('ALTER TABLE validation_result ADD CONSTRAINT FK_VALIDATION_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE validation_result ADD CONSTRAINT FK_VALIDATION_SELLER FOREIGN KEY (seller_id) REFERENCES student (id)');
        $this->addSql('ALTER TABLE availability DROP FOREIGN KEY FK_3FB7A2BF41807E1D');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDE613FECDF');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDEA76ED395');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDEF1FAD9D3');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDE41807E1D');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDED62B0FA');
        $this->addSql('ALTER TABLE bundle DROP FOREIGN KEY FK_A57B32FDCB944F1A');
        $this->addSql('ALTER TABLE bundle DROP FOREIGN KEY FK_A57B32FD41807E1D');
        $this->addSql('ALTER TABLE bundle_usage DROP FOREIGN KEY FK_4BB3EBDBF1FAD9D3');
        $this->addSql('ALTER TABLE bundle_usage DROP FOREIGN KEY FK_4BB3EBDB3301C60');
        $this->addSql('ALTER TABLE course_category DROP FOREIGN KEY FK_AFF87497591CC992');
        $this->addSql('ALTER TABLE course_category DROP FOREIGN KEY FK_AFF8749712469DE2');
        $this->addSql('ALTER TABLE course_test DROP FOREIGN KEY FK_10DDA30A591CC992');
        $this->addSql('ALTER TABLE course_test_question DROP FOREIGN KEY FK_E01906C1169E01B5');
        $this->addSql('ALTER TABLE course_test_result DROP FOREIGN KEY FK_F0DDF6E9A76ED395');
        $this->addSql('ALTER TABLE course_test_result DROP FOREIGN KEY FK_F0DDF6E9169E01B5');
        $this->addSql('ALTER TABLE learning_roadmap DROP FOREIGN KEY FK_A7645600A76ED395');
        $this->addSql('ALTER TABLE lesson_completion DROP FOREIGN KEY FK_35DF7EAFA76ED395');
        $this->addSql('ALTER TABLE lesson_completion DROP FOREIGN KEY FK_35DF7EAFCDF80196');
        $this->addSql('ALTER TABLE lesson_completion DROP FOREIGN KEY FK_35DF7EAF591CC992');
        $this->addSql('ALTER TABLE meeting_feedback DROP FOREIGN KEY FK_41B8698D3301C60');
        $this->addSql('ALTER TABLE meeting_feedback DROP FOREIGN KEY FK_41B8698DA76ED395');
        $this->addSql('ALTER TABLE quiz_statistics DROP FOREIGN KEY FK_ABBCAC1E853CD175');
        $this->addSql('ALTER TABLE quiz_statistics DROP FOREIGN KEY FK_ABBCAC1ECB944F1A');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C68B567663');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6CB944F1A');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C641807E1D');
        $this->addSql('ALTER TABLE role_permissions DROP FOREIGN KEY FK_1FBA94E6D60322AC');
        $this->addSql('ALTER TABLE role_permissions DROP FOREIGN KEY FK_1FBA94E6FED90CCA');
        $this->addSql('ALTER TABLE teacher_profile DROP FOREIGN KEY FK_4C95274EA76ED395');
        $this->addSql('ALTER TABLE time_slot DROP FOREIGN KEY FK_1B3294A61778466');
        $this->addSql('ALTER TABLE tutoring_session DROP FOREIGN KEY FK_DD9D67613301C60');
        $this->addSql('ALTER TABLE user_badge DROP FOREIGN KEY FK_1C32B345A76ED395');
        $this->addSql('ALTER TABLE user_badge DROP FOREIGN KEY FK_1C32B345F7A2C2FC');
        $this->addSql('ALTER TABLE user_points DROP FOREIGN KEY FK_42E89514A76ED395');
        $this->addSql('ALTER TABLE user_points DROP FOREIGN KEY FK_42E89514C2C9318D');
        $this->addSql('DROP TABLE availability');
        $this->addSql('DROP TABLE badge');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE bundle');
        $this->addSql('DROP TABLE bundle_usage');
        $this->addSql('DROP TABLE course_category');
        $this->addSql('DROP TABLE course_test');
        $this->addSql('DROP TABLE course_test_question');
        $this->addSql('DROP TABLE course_test_result');
        $this->addSql('DROP TABLE learning_roadmap');
        $this->addSql('DROP TABLE lesson_completion');
        $this->addSql('DROP TABLE meeting_feedback');
        $this->addSql('DROP TABLE permissions');
        $this->addSql('DROP TABLE quiz_statistics');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE role_permissions');
        $this->addSql('DROP TABLE teacher_profile');
        $this->addSql('DROP TABLE time_slot');
        $this->addSql('DROP TABLE tutoring_session');
        $this->addSql('DROP TABLE user_badge');
        $this->addSql('DROP TABLE user_level');
        $this->addSql('DROP TABLE user_points');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1BE04EA9');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC18545BDF5');
        $this->addSql('CREATE INDEX IDX_APPLICATION_STATUS ON application (status)');
        $this->addSql('DROP INDEX idx_a45bddc1be04ea9 ON application');
        $this->addSql('CREATE INDEX IDX_APPLICATION_JOB ON application (job_id)');
        $this->addSql('DROP INDEX idx_a45bddc18545bdf5 ON application');
        $this->addSql('CREATE INDEX IDX_APPLICATION_FREELANCER ON application (freelancer_id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1BE04EA9 FOREIGN KEY (job_id) REFERENCES job (id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC18545BDF5 FOREIGN KEY (freelancer_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE category CHANGE name name VARCHAR(120) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CATEGORY_NAME ON category (name)');
        $this->addSql('DROP INDEX uniq_64c19c1989d9b62 ON category');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CATEGORY_SLUG ON category (slug)');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_219CDA4AA76ED395');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_219CDA4A1C7C7A5');
        $this->addSql('DROP INDEX IDX_219CDA4AA76ED395 ON certificate');
        $this->addSql('DROP INDEX IDX_219CDA4A1C7C7A5 ON certificate');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_219CDA4A591CC992');
        $this->addSql('ALTER TABLE certificate ADD student_id INT NOT NULL, ADD quiz_id INT DEFAULT NULL, ADD verification_code VARCHAR(64) NOT NULL, ADD pdf_file VARCHAR(255) DEFAULT NULL, DROP user_id, DROP quiz_result_id, DROP filename, DROP file_path, DROP file_size, DROP is_downloaded, DROP last_downloaded_at, DROP download_count, CHANGE course_id course_id INT DEFAULT NULL, CHANGE generated_at issued_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_CERTIFICATE_QUIZ FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_CERTIFICATE_STUDENT FOREIGN KEY (student_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_CERTIFICATE_QUIZ ON certificate (quiz_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CERTIFICATE_CODE ON certificate (verification_code)');
        $this->addSql('CREATE INDEX IDX_CERTIFICATE_STUDENT ON certificate (student_id)');
        $this->addSql('DROP INDEX idx_219cda4a591cc992 ON certificate');
        $this->addSql('CREATE INDEX IDX_CERTIFICATE_COURSE ON certificate (course_id)');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_219CDA4A591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE chapter ADD position INT DEFAULT 0, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE sort_order sort_order INT DEFAULT 0');
        $this->addSql('ALTER TABLE checkout ADD user_id INT NOT NULL, ADD transaction_id VARCHAR(255) DEFAULT NULL, DROP first_name, DROP last_name, DROP email, DROP phone, DROP address, DROP city, DROP state, DROP zip_code, DROP country, DROP card_number, DROP expiry_date, DROP cvv, DROP cardholder_name, DROP agree_terms, CHANGE payment_method payment_method VARCHAR(50) DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT \'pending\', CHANGE total_amount total_amount DOUBLE PRECISION NOT NULL');
        $this->addSql('ALTER TABLE checkout ADD CONSTRAINT FK_CHECKOUT_USER FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_CHECKOUT_USER ON checkout (user_id)');
        $this->addSql('ALTER TABLE contact ADD name VARCHAR(255) NOT NULL, DROP first_name, DROP last_name, DROP phone, CHANGE subject subject VARCHAR(255) NOT NULL, CHANGE status status VARCHAR(20) DEFAULT \'pending\'');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB9A76ED395');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB912469DE2');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB9A76ED395');
        $this->addSql('ALTER TABLE course ADD slug VARCHAR(255) NOT NULL, ADD is_published TINYINT(1) DEFAULT 0 NOT NULL, ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE level level VARCHAR(50) NOT NULL, CHANGE price price DOUBLE PRECISION NOT NULL, CHANGE status status VARCHAR(20) DEFAULT \'draft\' NOT NULL, CHANGE image_status image_status VARCHAR(20) DEFAULT \'pending\', CHANGE video_status video_status VARCHAR(20) DEFAULT \'pending\', CHANGE image_progress image_progress DOUBLE PRECISION DEFAULT \'0\', CHANGE video_progress video_progress DOUBLE PRECISION DEFAULT \'0\'');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_COURSE_USER FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_COURSE_STATUS ON course (status)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_COURSE_SLUG ON course (slug)');
        $this->addSql('CREATE INDEX IDX_COURSE_PUBLISHED ON course (is_published)');
        $this->addSql('DROP INDEX idx_169e6fb9a76ed395 ON course');
        $this->addSql('CREATE INDEX IDX_COURSE_USER ON course (user_id)');
        $this->addSql('DROP INDEX idx_169e6fb912469de2 ON course');
        $this->addSql('CREATE INDEX IDX_COURSE_CATEGORY ON course (category_id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB912469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE course_lesson DROP FOREIGN KEY FK_564CB5BE591CC992');
        $this->addSql('ALTER TABLE course_lesson DROP FOREIGN KEY FK_564CB5BECDF80196');
        $this->addSql('ALTER TABLE course_lesson DROP FOREIGN KEY FK_564CB5BE591CC992');
        $this->addSql('ALTER TABLE course_lesson DROP FOREIGN KEY FK_564CB5BECDF80196');
        $this->addSql('ALTER TABLE course_lesson ADD title VARCHAR(255) NOT NULL, ADD content LONGTEXT DEFAULT NULL, DROP created_at, CHANGE lesson_id lesson_id INT DEFAULT NULL, CHANGE sort_order position INT NOT NULL');
        $this->addSql('ALTER TABLE course_lesson ADD CONSTRAINT FK_COURSE_LESSON_COURSE FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course_lesson ADD CONSTRAINT FK_COURSE_LESSON_LESSON FOREIGN KEY (lesson_id) REFERENCES lesson (id) ON DELETE SET NULL');
        $this->addSql('DROP INDEX idx_564cb5be591cc992 ON course_lesson');
        $this->addSql('CREATE INDEX IDX_COURSE_LESSON_COURSE ON course_lesson (course_id)');
        $this->addSql('DROP INDEX idx_564cb5becdf80196 ON course_lesson');
        $this->addSql('CREATE INDEX IDX_COURSE_LESSON_LESSON ON course_lesson (lesson_id)');
        $this->addSql('ALTER TABLE course_lesson ADD CONSTRAINT FK_564CB5BE591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE course_lesson ADD CONSTRAINT FK_564CB5BECDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id)');
        $this->addSql('ALTER TABLE course_review DROP FOREIGN KEY FK_D77B408BA76ED395');
        $this->addSql('DROP INDEX IDX_D77B408BA76ED395 ON course_review');
        $this->addSql('ALTER TABLE course_review DROP FOREIGN KEY FK_D77B408B591CC992');
        $this->addSql('ALTER TABLE course_review CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE user_id student_id INT NOT NULL');
        $this->addSql('ALTER TABLE course_review ADD CONSTRAINT FK_REVIEW_STUDENT FOREIGN KEY (student_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_REVIEW_STUDENT ON course_review (student_id)');
        $this->addSql('DROP INDEX idx_d77b408b591cc992 ON course_review');
        $this->addSql('CREATE INDEX IDX_REVIEW_COURSE ON course_review (course_id)');
        $this->addSql('ALTER TABLE course_review ADD CONSTRAINT FK_D77B408B591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE enrollment DROP FOREIGN KEY FK_DBDCD7E1A76ED395');
        $this->addSql('ALTER TABLE enrollment DROP FOREIGN KEY FK_DBDCD7E1CB7D0048');
        $this->addSql('DROP INDEX IDX_DBDCD7E1A76ED395 ON enrollment');
        $this->addSql('DROP INDEX IDX_DBDCD7E1CB7D0048 ON enrollment');
        $this->addSql('DROP INDEX IDX_DBDCD7E1A2BAD590 ON enrollment');
        $this->addSql('ALTER TABLE enrollment DROP FOREIGN KEY FK_DBDCD7E1591CC992');
        $this->addSql('ALTER TABLE enrollment ADD student_id INT NOT NULL, ADD progress_percent INT DEFAULT NULL, DROP starting_lesson_id, DROP placement_test_result_id, DROP ip_address, DROP user_agent, CHANGE user_id user_id INT DEFAULT NULL, CHANGE enrolled_at enrolled_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE status status VARCHAR(20) DEFAULT \'active\', CHANGE progress progress DOUBLE PRECISION DEFAULT \'0\', CHANGE placement_test_taken is_completed TINYINT(1) DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_ENROLLMENT_STUDENT FOREIGN KEY (student_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_ENROLLMENT_STUDENT ON enrollment (student_id)');
        $this->addSql('DROP INDEX idx_dbdcd7e1591cc992 ON enrollment');
        $this->addSql('CREATE INDEX IDX_ENROLLMENT_COURSE ON enrollment (course_id)');
        $this->addSql('ALTER TABLE enrollment ADD CONSTRAINT FK_DBDCD7E1591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE favorite DROP FOREIGN KEY FK_68C58ED9A76ED395');
        $this->addSql('ALTER TABLE favorite DROP FOREIGN KEY FK_68C58ED9BE04EA9');
        $this->addSql('DROP INDEX idx_68c58ed9a76ed395 ON favorite');
        $this->addSql('CREATE INDEX IDX_FAVORITE_USER ON favorite (user_id)');
        $this->addSql('DROP INDEX idx_68c58ed9be04ea9 ON favorite');
        $this->addSql('CREATE INDEX IDX_FAVORITE_JOB ON favorite (job_id)');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED9BE04EA9 FOREIGN KEY (job_id) REFERENCES job (id)');
        $this->addSql('DROP INDEX UNIQ_FBD8E0F8989D9B62 ON job');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_FBD8E0F819EB6921');
        $this->addSql('ALTER TABLE job DROP location, DROP type, DROP experience_level, DROP duration, DROP requirements, DROP skills, DROP slug');
        $this->addSql('CREATE INDEX IDX_JOB_STATUS ON job (status)');
        $this->addSql('DROP INDEX idx_fbd8e0f819eb6921 ON job');
        $this->addSql('CREATE INDEX IDX_JOB_CLIENT ON job (client_id)');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F819EB6921 FOREIGN KEY (client_id) REFERENCES user (id)');
        $this->addSql('DROP INDEX idx_lesson_sort ON lesson');
        $this->addSql('ALTER TABLE lesson ADD position INT DEFAULT 0, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', DROP type, DROP attachment_url, DROP difficulty, DROP learning_objectives, DROP prerequisites, DROP materials, DROP estimated_time, DROP transcript, DROP thumbnail_url, DROP resources, DROP assessment, DROP is_completed, DROP views, DROP published_at, DROP status, DROP description, DROP sort_order, CHANGE duration duration VARCHAR(255) DEFAULT NULL, CHANGE is_preview is_preview TINYINT(1) DEFAULT 0');
        $this->addSql('DROP INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages');
        $this->addSql('CREATE INDEX IDX_MESSENGER_QUEUE ON messenger_messages (queue_name, available_at, delivered_at)');
        $this->addSql('ALTER TABLE notification ADD user_id INT NOT NULL, ADD type VARCHAR(50) NOT NULL, ADD message LONGTEXT NOT NULL, ADD is_read TINYINT(1) DEFAULT 0, DROP status, CHANGE email title VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_NOTIFICATION_USER FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_NOTIFICATION_USER ON notification (user_id)');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F52993984584665A');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F52993986C755722');
        $this->addSql('ALTER TABLE `order` CHANGE total_price total_price DOUBLE PRECISION NOT NULL');
        $this->addSql('CREATE INDEX IDX_ORDER_STATUS ON `order` (status)');
        $this->addSql('DROP INDEX idx_f52993986c755722 ON `order`');
        $this->addSql('CREATE INDEX IDX_ORDER_BUYER ON `order` (buyer_id)');
        $this->addSql('DROP INDEX idx_f52993984584665a ON `order`');
        $this->addSql('CREATE INDEX IDX_ORDER_PRODUCT ON `order` (product_id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F52993984584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F52993986C755722 FOREIGN KEY (buyer_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD12469DE2');
        $this->addSql('DROP INDEX IDX_D34A04AD12469DE2 ON product');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD8545BDF5');
        $this->addSql('ALTER TABLE product ADD category VARCHAR(255) NOT NULL, DROP category_id, CHANGE price price DOUBLE PRECISION NOT NULL');
        $this->addSql('CREATE INDEX IDX_PRODUCT_CATEGORY ON product (category)');
        $this->addSql('DROP INDEX uniq_d34a04ad989d9b62 ON product');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PRODUCT_SLUG ON product (slug)');
        $this->addSql('DROP INDEX idx_d34a04ad8545bdf5 ON product');
        $this->addSql('CREATE INDEX IDX_PRODUCT_FREELANCER ON product (freelancer_id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD8545BDF5 FOREIGN KEY (freelancer_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE question DROP FOREIGN KEY FK_B6F7494E853CD175');
        $this->addSql('ALTER TABLE question DROP FOREIGN KEY FK_B6F7494E853CD175');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_QUESTION_QUIZ_LEGACY FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('DROP INDEX idx_b6f7494e853cd175 ON question');
        $this->addSql('CREATE INDEX IDX_QUESTION_QUIZ_LEGACY ON question (quiz_id)');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494E853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz DROP FOREIGN KEY FK_A412FA92591CC992');
        $this->addSql('ALTER TABLE quiz DROP FOREIGN KEY FK_A412FA92591CC992');
        $this->addSql('ALTER TABLE quiz ADD slug VARCHAR(255) NOT NULL, ADD time_limit_minutes INT DEFAULT 60 NOT NULL, ADD is_published TINYINT(1) DEFAULT 1 NOT NULL, DROP quiz_type, CHANGE course_id course_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE quiz ADD CONSTRAINT FK_QUIZ_COURSE FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_QUIZ_SLUG ON quiz (slug)');
        $this->addSql('DROP INDEX idx_a412fa92591cc992 ON quiz');
        $this->addSql('CREATE INDEX IDX_QUIZ_COURSE ON quiz (course_id)');
        $this->addSql('ALTER TABLE quiz ADD CONSTRAINT FK_A412FA92591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_answer DROP FOREIGN KEY FK_3799BA7C1E27F6BF');
        $this->addSql('ALTER TABLE quiz_answer DROP FOREIGN KEY FK_3799BA7C1C7C7A5');
        $this->addSql('DROP INDEX IDX_3799BA7C1C7C7A5 ON quiz_answer');
        $this->addSql('ALTER TABLE quiz_answer DROP FOREIGN KEY FK_3799BA7C1E27F6BF');
        $this->addSql('ALTER TABLE quiz_answer ADD content VARCHAR(255) NOT NULL, DROP quiz_result_id, DROP answer, DROP created_at, CHANGE is_correct is_correct TINYINT(1) DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE quiz_answer ADD CONSTRAINT FK_ANSWER_QUESTION FOREIGN KEY (question_id) REFERENCES quiz_question (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_3799ba7c1e27f6bf ON quiz_answer');
        $this->addSql('CREATE INDEX IDX_ANSWER_QUESTION ON quiz_answer (question_id)');
        $this->addSql('ALTER TABLE quiz_answer ADD CONSTRAINT FK_3799BA7C1E27F6BF FOREIGN KEY (question_id) REFERENCES quiz_question (id)');
        $this->addSql('ALTER TABLE quiz_attempt DROP FOREIGN KEY FK_AB6AFC6A76ED395');
        $this->addSql('DROP INDEX IDX_AB6AFC6A76ED395 ON quiz_attempt');
        $this->addSql('ALTER TABLE quiz_attempt DROP FOREIGN KEY FK_AB6AFC6853CD175');
        $this->addSql('ALTER TABLE quiz_attempt ADD student_id INT NOT NULL, ADD finished_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD max_score INT DEFAULT NULL, DROP user_id, DROP total_questions, DROP correct_answers, DROP completed_at, DROP status, CHANGE score score INT DEFAULT NULL, CHANGE started_at started_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE quiz_attempt ADD CONSTRAINT FK_ATTEMPT_STUDENT FOREIGN KEY (student_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_ATTEMPT_STUDENT ON quiz_attempt (student_id)');
        $this->addSql('DROP INDEX idx_ab6afc6853cd175 ON quiz_attempt');
        $this->addSql('CREATE INDEX IDX_ATTEMPT_QUIZ ON quiz_attempt (quiz_id)');
        $this->addSql('ALTER TABLE quiz_attempt ADD CONSTRAINT FK_AB6AFC6853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('ALTER TABLE quiz_question DROP FOREIGN KEY FK_6033B00B853CD175');
        $this->addSql('ALTER TABLE quiz_question DROP FOREIGN KEY FK_6033B00B853CD175');
        $this->addSql('ALTER TABLE quiz_question ADD position INT NOT NULL, DROP explanation, DROP options, DROP correct_answer, DROP points, DROP created_at, CHANGE question content LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE quiz_question ADD CONSTRAINT FK_QUESTION_QUIZ FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_6033b00b853cd175 ON quiz_question');
        $this->addSql('CREATE INDEX IDX_QUESTION_QUIZ ON quiz_question (quiz_id)');
        $this->addSql('ALTER TABLE quiz_question ADD CONSTRAINT FK_6033B00B853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('ALTER TABLE quiz_result DROP FOREIGN KEY FK_FE2E314AA76ED395');
        $this->addSql('ALTER TABLE quiz_result DROP FOREIGN KEY FK_FE2E314A853CD175');
        $this->addSql('DROP INDEX idx_fe2e314aa76ed395 ON quiz_result');
        $this->addSql('CREATE INDEX IDX_RESULT_USER ON quiz_result (user_id)');
        $this->addSql('DROP INDEX idx_fe2e314a853cd175 ON quiz_result');
        $this->addSql('CREATE INDEX IDX_RESULT_QUIZ ON quiz_result (quiz_id)');
        $this->addSql('ALTER TABLE quiz_result ADD CONSTRAINT FK_FE2E314AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE quiz_result ADD CONSTRAINT FK_FE2E314A853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('ALTER TABLE quiz_settings DROP FOREIGN KEY FK_33815980853CD175');
        $this->addSql('DROP INDEX IDX_33815980853CD175 ON quiz_settings');
        $this->addSql('ALTER TABLE quiz_settings ADD show_answers TINYINT(1) DEFAULT 1, ADD shuffle_questions TINYINT(1) DEFAULT 0, DROP quiz_id, DROP points, CHANGE time_limit time_limit INT DEFAULT 60, CHANGE passing_score passing_score INT DEFAULT 70, CHANGE max_attempts max_attempts INT DEFAULT 3');
        $this->addSql('ALTER TABLE roles DROP description');
        $this->addSql('ALTER TABLE session DROP FOREIGN KEY FK_D044D5D412469DE2');
        $this->addSql('DROP INDEX IDX_D044D5D412469DE2 ON session');
        $this->addSql('ALTER TABLE session DROP FOREIGN KEY FK_D044D5D48C4FC193');
        $this->addSql('ALTER TABLE session ADD title VARCHAR(255) NOT NULL, ADD description LONGTEXT DEFAULT NULL, ADD start_time DATETIME NOT NULL, ADD end_time DATETIME NOT NULL, ADD max_participants INT DEFAULT 1, ADD price DOUBLE PRECISION DEFAULT \'0\', ADD status VARCHAR(20) DEFAULT \'available\', ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', DROP category_id, DROP name, DROP level, DROP date, DROP start_date, DROP end_date, DROP duration, DROP session_description, DROP available_from, DROP available_to, DROP hourly_price, CHANGE instructor_id instructor_id INT NOT NULL');
        $this->addSql('DROP INDEX idx_d044d5d48c4fc193 ON session');
        $this->addSql('CREATE INDEX IDX_SESSION_INSTRUCTOR ON session (instructor_id)');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D48C4FC193 FOREIGN KEY (instructor_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649D60322AC');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649D60322AC');
        $this->addSql('ALTER TABLE user ADD name VARCHAR(255) NOT NULL, ADD avatar VARCHAR(255) DEFAULT NULL, ADD address VARCHAR(255) DEFAULT NULL, ADD email_verified TINYINT(1) DEFAULT 0, ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', DROP google_id, DROP facebook_id, DROP reset_token, DROP reset_token_expires_at, DROP face_encoding, DROP face_enabled, DROP income, CHANGE full_name full_name VARCHAR(100) DEFAULT NULL, CHANGE email email VARCHAR(180) NOT NULL, CHANGE agree_terms agree_terms TINYINT(1) DEFAULT 0, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_USER_ROLE FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE SET NULL');
        $this->addSql('DROP INDEX uniq_8d93d649e7927c74 ON user');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_EMAIL ON user (email)');
        $this->addSql('DROP INDEX idx_8d93d649d60322ac ON user');
        $this->addSql('CREATE INDEX IDX_USER_ROLE ON user (role_id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649D60322AC FOREIGN KEY (role_id) REFERENCES roles (id)');
    }
}
