<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I4JdL2WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i4JdL2W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'courseRepository' => ['privates', 'App\\Repository\\CourseRepository', 'getCourseRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'courseRepository' => 'App\\Repository\\CourseRepository',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.i4JdL2W'])) {
            return $container->privates['.service_locator.i4JdL2W'];
        }

        return $container->privates['.service_locator.i4JdL2W'] = $instance;
    }
}
