<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__TJ9rtwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..TJ9rtw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'studentRepository' => ['privates', 'App\\Repository\\StudentRepository', 'getStudentRepositoryService', true],
        ], [
            'paginator' => '?',
            'studentRepository' => 'App\\Repository\\StudentRepository',
        ]);

        if (isset($container->privates['.service_locator..TJ9rtw'])) {
            return $container->privates['.service_locator..TJ9rtw'];
        }

        return $container->privates['.service_locator..TJ9rtw'] = $instance;
    }
}
