<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ByeX9_DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ByeX9.D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ByeX9.D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bookingRepository' => ['privates', 'App\\Repository\\BookingRepository', 'getBookingRepositoryService', true],
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'roleRepository' => ['privates', 'App\\Repository\\RoleRepository', 'getRoleRepositoryService', true],
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'bookingRepository' => 'App\\Repository\\BookingRepository',
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'roleRepository' => 'App\\Repository\\RoleRepository',
            'sessionRepository' => 'App\\Repository\\SessionRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
