<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0HMz9_VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0HMz9.v' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'category' => ['privates', '.errored..service_locator.0HMz9.v.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.0HMz9.v": it needs an instance of "App\\Entity\\Category" but this type has been excluded in "config/services.yaml".'],
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'category' => 'App\\Entity\\Category',
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'csrfTokenManager' => '?',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.0HMz9.v'])) {
            return $container->privates['.service_locator.0HMz9.v'];
        }

        return $container->privates['.service_locator.0HMz9.v'] = $instance;
    }
}
