<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GC7VyPfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GC7VyPf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'jobRepository' => ['privates', 'App\\Repository\\JobRepository', 'getJobRepositoryService', true],
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'entityManager' => '?',
            'jobRepository' => 'App\\Repository\\JobRepository',
            'orderRepository' => 'App\\Repository\\OrderRepository',
            'productRepository' => 'App\\Repository\\ProductRepository',
        ]);

        if (isset($container->privates['.service_locator.GC7VyPf'])) {
            return $container->privates['.service_locator.GC7VyPf'];
        }

        return $container->privates['.service_locator.GC7VyPf'] = $instance;
    }
}
