<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yu1STzgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Yu1STzg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'course' => ['privates', '.errored..service_locator.Yu1STzg.App\\Entity\\Course', NULL, 'Cannot autowire service ".service_locator.Yu1STzg": it needs an instance of "App\\Entity\\Course" but this type has been excluded in "config/services.yaml".'],
            'courseRepository' => ['privates', 'App\\Repository\\CourseRepository', 'getCourseRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'course' => 'App\\Entity\\Course',
            'courseRepository' => 'App\\Repository\\CourseRepository',
            'entityManager' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);

        if (isset($container->privates['.service_locator.Yu1STzg'])) {
            return $container->privates['.service_locator.Yu1STzg'];
        }

        return $container->privates['.service_locator.Yu1STzg'] = $instance;
    }
}
