<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PiVMNXJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.piVMNXJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'student' => ['privates', '.errored..service_locator.piVMNXJ.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.piVMNXJ": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'student' => 'App\\Entity\\User',
        ]);

        if (isset($container->privates['.service_locator.piVMNXJ'])) {
            return $container->privates['.service_locator.piVMNXJ'];
        }

        return $container->privates['.service_locator.piVMNXJ'] = $instance;
    }
}
