<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S2tfu9NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S2tfu9N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'job' => ['privates', '.errored..service_locator.S2tfu9N.App\\Entity\\Job', NULL, 'Cannot autowire service ".service_locator.S2tfu9N": it needs an instance of "App\\Entity\\Job" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'job' => 'App\\Entity\\Job',
        ]);

        if (isset($container->privates['.service_locator.S2tfu9N'])) {
            return $container->privates['.service_locator.S2tfu9N'];
        }

        return $container->privates['.service_locator.S2tfu9N'] = $instance;
    }
}
