<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1qq2EwNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1qq2EwN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'course' => ['privates', '.errored..service_locator.1qq2EwN.App\\Entity\\Course', NULL, 'Cannot autowire service ".service_locator.1qq2EwN": it needs an instance of "App\\Entity\\Course" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'course' => 'App\\Entity\\Course',
            'entityManager' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);

        if (isset($container->privates['.service_locator.1qq2EwN'])) {
            return $container->privates['.service_locator.1qq2EwN'];
        }

        return $container->privates['.service_locator.1qq2EwN'] = $instance;
    }
}
