<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fn_QVAjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Fn.QVAj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'favoriteRepository' => ['privates', 'App\\Repository\\FavoriteRepository', 'getFavoriteRepositoryService', true],
            'job' => ['privates', '.errored..service_locator.Fn.QVAj.App\\Entity\\Job', NULL, 'Cannot autowire service ".service_locator.Fn.QVAj": it needs an instance of "App\\Entity\\Job" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'favoriteRepository' => 'App\\Repository\\FavoriteRepository',
            'job' => 'App\\Entity\\Job',
        ]);

        if (isset($container->privates['.service_locator.Fn.QVAj'])) {
            return $container->privates['.service_locator.Fn.QVAj'];
        }

        return $container->privates['.service_locator.Fn.QVAj'] = $instance;
    }
}
