<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K9pe1RpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k9pe1Rp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
        ], [
            'entityManager' => '?',
            'orderRepository' => 'App\\Repository\\OrderRepository',
        ]);

        if (isset($container->privates['.service_locator.k9pe1Rp'])) {
            return $container->privates['.service_locator.k9pe1Rp'];
        }

        return $container->privates['.service_locator.k9pe1Rp'] = $instance;
    }
}
