<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_75wPQAIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.75wPQAI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.75wPQAI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'job' => ['privates', '.errored..service_locator.75wPQAI.App\\Entity\\Job', NULL, 'Cannot autowire service ".service_locator.75wPQAI": it needs an instance of "App\\Entity\\Job" but this type has been excluded in "config/services.yaml".'],
        ], [
            'job' => 'App\\Entity\\Job',
        ]);
    }
}
