<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5lZJVBzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5lZJVBz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'orderRepository' => 'App\\Repository\\OrderRepository',
            'paginator' => '?',
        ]);

        if (isset($container->privates['.service_locator.5lZJVBz'])) {
            return $container->privates['.service_locator.5lZJVBz'];
        }

        return $container->privates['.service_locator.5lZJVBz'] = $instance;
    }
}
