<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N7dcDh9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N7dcDh9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'product' => ['privates', '.errored..service_locator.N7dcDh9.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.N7dcDh9": it needs an instance of "App\\Entity\\Product" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'product' => 'App\\Entity\\Product',
        ]);

        if (isset($container->privates['.service_locator.N7dcDh9'])) {
            return $container->privates['.service_locator.N7dcDh9'];
        }

        return $container->privates['.service_locator.N7dcDh9'] = $instance;
    }
}
