<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FoG6PI4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.foG6PI4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
        ], [
            'em' => '?',
            'sessionRepository' => 'App\\Repository\\SessionRepository',
        ]);

        if (isset($container->privates['.service_locator.foG6PI4'])) {
            return $container->privates['.service_locator.foG6PI4'];
        }

        return $container->privates['.service_locator.foG6PI4'] = $instance;
    }
}
