<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OsAcUUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.osAcU_U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jobRepository' => ['privates', 'App\\Repository\\JobRepository', 'getJobRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'jobRepository' => 'App\\Repository\\JobRepository',
            'paginator' => '?',
        ]);

        if (isset($container->privates['.service_locator.osAcU_U'])) {
            return $container->privates['.service_locator.osAcU_U'];
        }

        return $container->privates['.service_locator.osAcU_U'] = $instance;
    }
}
