<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O89u0cAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O89u0cA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bookingRepository' => ['privates', 'App\\Repository\\BookingRepository', 'getBookingRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'bookingRepository' => 'App\\Repository\\BookingRepository',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.O89u0cA'])) {
            return $container->privates['.service_locator.O89u0cA'];
        }

        return $container->privates['.service_locator.O89u0cA'] = $instance;
    }
}
