<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSampleChaptersCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateSampleChaptersCommand' shared autowired service.
     *
     * @return \App\Command\CreateSampleChaptersCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'CreateSampleChaptersCommand.php';

        $container->privates['App\\Command\\CreateSampleChaptersCommand'] = $instance = new \App\Command\CreateSampleChaptersCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\CourseRepository'] ?? $container->load('getCourseRepositoryService')));

        $instance->setName('app:create-sample-chapters');
        $instance->setDescription('Create sample chapters and lessons for existing courses');

        return $instance;
    }
}
