<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJob4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.u36tywv.App\Entity\Job' shared service.
     *
     * @return \App\Entity\Job
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.u36tywv": it needs an instance of "App\\Entity\\Job" but this type has been excluded in "config/services.yaml".');
    }
}
