<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLessonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wOgpyQx.App\Entity\Lesson' shared service.
     *
     * @return \App\Entity\Lesson
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wOgpyQx": it needs an instance of "App\\Entity\\Lesson" but this type has been excluded in "config/services.yaml".');
    }
}
