<?php

namespace ContainerV4CjFRm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getYouTubeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\YouTubeController' shared autowired service.
     *
     * @return \App\Controller\YouTubeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'YouTubeController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'YouTubeService.php';

        $container->services['App\\Controller\\YouTubeController'] = $instance = new \App\Controller\YouTubeController(($container->privates['App\\Service\\YouTubeService'] ??= new \App\Service\YouTubeService($container->getEnv('GOOGLE_YOUTUBE_API_KEY'))), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->privates['App\\Repository\\LessonRepository'] ?? $container->load('getLessonRepositoryService')), ($container->privates['App\\Repository\\CourseRepository'] ?? $container->load('getCourseRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\YouTubeController', $container));

        return $instance;
    }
}
