<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV4CjFRm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV4CjFRm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV4CjFRm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV4CjFRm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV4CjFRm\App_KernelDevDebugContainer([
    'container.build_hash' => 'V4CjFRm',
    'container.build_id' => 'aabfe62f',
    'container.build_time' => 1771769383,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV4CjFRm');
